### ISSUE TITLE
Map Transition Bug

### ISSUE THREAD

**Issue by andrewhong04** [Tuxemon/Tuxemon#1050]
**Describe the bug**
You would get teleported to the wrong location if you hold down a key during a fade transition from map to map

**To Reproduce**
If you go downstairs upon startup, hold whatever key you were pressing and you'll be teleported to an unexpected location.

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/35881688/141217633-65708219-7e6d-46ab-9282-274ee4d488fb.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Python Version [3.8.5]

**Smartphone (please complete the following information):**
 - Device: [n/a]
 - OS: [n/a]

**Additional context**
n/a

**Comment by andrewhong04** [comment]
Update: I tried reproducing this again, but it looks like it's a frame-perfect sort of thing? It has a 50/50 chance of working on my laptop.

**Comment by magmaus3** [comment]
What versions of libraries do you use?
You can check them using `pip list` or `python -m pip list`.

**Comment by andrewhong04** [comment]
Sorry for the late reply, here are my libraries
https://www.toptal.com/developers/hastebin/qujagujada.apache

**Comment by ultidonki** [comment]
I think this is a duplicate of #994 
I think it was also more likely to happen if you were using full-screen? Or at least a larger resolution? 

novialriptide, you're right, it seems like a frame-perfect bug. 
If I change the transition times to take 0.5 seconds, it never happens. If I change the teleport_transition times to take 0.1 seconds, it always happens. 

From #994, I think this was the latest update: 
"As discussed on the Matrix/Discord bridge, this part of the system might be re-written soon, which might fix the problem"
I haven't heard anyone mention it since then. In my mod, I've just got around it by using teleport_transition times of 0.5 seconds.

**Comment by andrewhong04** [comment]
This could be a duplicate, but I wasn't playing on full screen at the time.
