### ISSUE TITLE
Add Random_variable action 

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1074]
**Is your feature request related to a problem? Please describe.**
It would be fun for mappers to have a way to create random variables, and then do different events/actions depending on those random variables. 
They could do things like lotteries, random effects if you drink 'magic water', get a random tuxemon from a vending machine... etc. 

**Describe the solution you'd like**
A new action, with syntax similar to:
```random_variable variable_name,integer_number```
That sets variable_name in the player variables dictionary to a random number below integer_number. 

It needs to be in the player variables dictionary, so mappers can check this variable later using cond. (See example .tmx at end of this post)

**Describe alternatives you've considered**
Instead of a comma in
```random_variable variable_name,number```
possibly use a colon, to make it match the set_variable syntax:
```set_variable variable_name:value```
This might make it easier, or more consistent for mappers to understand. Or it might confuse them? 

Also, consider whether the random number will be between 0, and integer_number - 1, or between 1 and integer number (inclusive). 
I would personally keep it consistent with python, and use 0 and integer_number -1, but that could confuse mappers if they don't know or want to learn programming. I'm happy either way. 

Here's a .tmx file showing the kinds of things mappers could do with it: 
It will say either 'heads' or 'tails' depending on a random number 
(after someone implements random_variable, obviously)
[test_random_variable.zip](https://github.com/Tuxemon/Tuxemon/files/7576139/test_random_variable.zip)

**Comment by vnmabus** [comment]
This is one of the things that would be possible if we allow to call python code in conditions and actions, like it is proposed in #1060.

**Comment by bitcraft** [comment]
its good to think about non-programmers here.  when asked "pick a random number between 1 and 4", im pretty sure the average person will consider the range to be inclusive, ie, the options are 1,2,3 and 4.  the random function should be like that.  im not sure how this will be used, but i think it would be more clear to require a start and an end range.
```
random_variable name:start,end
```
this would be consistent with `set_variable`, and the range of values is immediately known.

**Comment by vnmabus** [comment]
Is it much easier for a non-programmer `random_variable name:start,end`  rather than `exec name = random.randint(start, end)`?

**Comment by vnmabus** [comment]
Also, for most tasks, `choice` will be better for them: `exec name = random.choice(["Rockitten", "Hydrone", "Aardart"])`.

**Comment by bitcraft** [comment]
> Is it much easier for a non-programmer random_variable name:start,end rather than exec name = random.randint(start, end)?

I would say yes.  because there is less syntax and less words to know.  questions for a non-programmer would be:
- what is `random`?  (its a python module...whats a module?...how to i import from the game script?)
- when do i need to use parens?  why do other actions not require them?  (why are some actions not python actions, "exec")
- what is exec?
- do i really need to learn python?

i also don't want to open pandoras box here and allow any arbitrary python code in the maps.  the "eval condition" is imo, where we should be drawing the line because it allows for easy expression of complex checks.  the primary reason i have against allowing arbitrary code in the actions is maintainability.  if the game changes, we could easily break the map code.  refactoring or bug fixing is easy in an IDE because the code is organized well.  the maps won't be able to benefit from this without additional work.  another is ergonomics.  writing the map script in python means that you lose the benefits of type annotation, syntax checking, etc.  if it is a simple format, like the game script, then there is less syntax to manage.

The projects goals for programming and map scripting has always roughly been in 4 tiers, from least complicated to most:
- json: tweak the game database.  add custom items, monsters, npcs, etc.
- map script: simple list of actions, with conditions and a syntax that doesn't require any python or general programming experience.  map makers should be able to create an entire game here.
- events code: requires some python experience, but should not be complex.  a novice should be able to change game state during a game event, or check state during a condition.  map makers might need to add code here to implement some unique feature.
- python code base: should be intermediate or experienced.  map makers should never need to touch this code.

**Comment by bitcraft** [comment]
a `choice` action would be a good addition, too

**Comment by vnmabus** [comment]
> when do i need to use parens? why do other actions not require them? (why are some actions not python actions, "exec")

Well, that depends in the  syntax that we use for other actions. AFAIK, that syntax has not been "designed" but instead was chosen to make the parsing code simple (using `split`). That is noticeable in the way different actions deal differently with arguments, using commas, spaces or colons to separate arguments.

I think we should make a deliberate effort to choose a syntax that is simple for non programmers, yet powerful and non redundant. As (not necessarily optimal) examples, some scripting-like programs I used when I was a child, before learning a proper programming language:
- The map editor for the Tzar game. Here you could define events (similar to our conditions), actions and rules. Rules are the meat of the scripting system. They consisted in an expression (that could use operators, custom variables, special variables and events) and a list of actions to execute in order when the expression is true. Except from the expression part the rest was changed with an special UI, without dealing with text syntax. The operators in the expressions used C-like syntax (and for me, that was the most difficult part to master). A VERY interesting part of the editor was also the conversation editor, where you could configure conversations with choices and even conditions for different messages, or for choices to be available.
- Entidad3d game editor (https://www.entidad-3d.com/tutoriales/tutorial_entidad_3d/index.html, unfortunately, it is only in Spanish). Instead of rules, conditions and actions, this took a more programming-like approach. You could use Basic-like scripts with custom commands, usually in the form `ACCI <ACTION_NAME> <parameters>`. As with the current version of Tuxemon, the syntax for different actions was not completely uniform, which meant that you needed to have the tutorial always open to check. Conditions were implemented with explicit IF-ELSE structures.
- The Construct game engine (https://www.construct.net/en). I used the first version, they are now in the third. Here the system is similar to Tuxemon: events with conditions and actions. They also allow subevents, which I don't think we allow but shouldn't be too difficult. It again used a special UI to set parameters, so there is no syntax. You could descend to Python for more complex behaviours.

Also with my small brother I used:
- Kodu (http://www.kodugamelab.com/). With this even a 3 years old (yes, I am not kidding!) can implement complex behaviours. The system here is simple: several lines, with one condition (that could be ommited) and one action. Also "sublines" could be added using indentation, so that in practice you could check several conditions and several actions. The syntax is again UI-based, and nontextual (mainly because it every condition and action has an image, for kids that can't read yet). You could also have several "pages" with these lines, and either "call" a page (similar to a function call) or "move" to a page (similar to changing state in a finite state machine).
- Scratch (https://scratch.mit.edu/). This is essentially a visual programming language.

I think we should try to learn the advantages/disadvantages of these and other systems and try to design the scripting system to be easy for non-programmers instead of merely evolving it, IMHO. This should be probably moved to a different issue (sorry @ultidonki  for stealing your issue).

**Comment by vnmabus** [comment]
BTW, as a closer relative (because it also uses Pygame), the Ren'Py engine for visual novels (https://www.renpy.org/), also allows calling arbitrary Python code, using a `$` prefix for the line.
