### ISSUE TITLE
Walk through walls

### ISSUE THREAD

**Issue by luckymouse0** [Tuxemon/Tuxemon#114]
I was moving my character when I tried to move the window at the same time, while keeping the movement button pressed. 

If you keep selecting the window, you can walk trough walls. The input is still being read. 

![wall bug](https://cloud.githubusercontent.com/assets/15199042/14730187/a67a52d2-081a-11e6-8234-da48c18ae488.png)

**Comment by bitcraft** [comment]
(off topic) Is this windows 2000?  I haven't seen that blue gradient title bar in years.

**Comment by luckymouse0** [comment]
[off topic] LOL ! Nope, It is windows 7 without visual effect (Adjust for best performance) :)

**Comment by bitcraft** [comment]
Interesting use case.  so with one hand you were moving the window, and the other you were pressing the arrow key?

**Comment by luckymouse0** [comment]
Right hand was moving the mouse,
Left hand was pressing right button.
I know it my sound crazy, but that how it was! =)

**Comment by ShadowApex** [comment]
Nice catch! This is a small edge case, but should definitely be looked at. Thanks for finding this!

**Comment by bitcraft** [comment]
I've looked into this a little bit so far.  The crux of the issue seems to be that the game clock will act erratically, enabling the player to move through walls because of an inconsistent timestep.  This isn't easily fixed unless we can detect if the user is dragging the window.  Unfortunately, though SDL does have a way to detect that, it isn't exposed through pygame.

One possible work around would be to fix the timestep and actively monitor the clock to check for odd values, possibly pausing the game, slowing down, etc.

**Comment by ShadowApex** [comment]
> One possible work around would be to fix the timestep and actively monitor the clock to check for odd values, possibly pausing the game, slowing down, etc.

This would probably be the most promising fix. We'd just need to put a cap on the [`time_delta`](https://github.com/Tuxemon/Tuxemon/blob/master/tuxemon/core/control.py#L534) value where it can't exceed a certain value. In order to prevent the player's movement to be greater than a tile's width in a single time step, the top limit of `time_delta` should be set to less than the [tile size](https://github.com/Tuxemon/Tuxemon/blob/master/tuxemon/core/prepare.py#L74) divided by the [player's walking speed in seconds](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/player.py#L100).

```python
time_delta = tile_size / player walking speed per second
```

In `core.control`, we can put in a conditional statement to check if the `time_delta` is greater than this value and limit it accordingly if it is exceeded.

**Comment by Airon90** [comment]
Is this bug fixed? I tested it and when the window is moved the player doesn't move

**Comment by bitcraft** [comment]
I just tested this bug and it still exists.  Here is how to trigger the bug:

- Stand in middle of room
- Begin walking towards a wall, continue to hold arrow key
- When player is one tile or less away from wall, click and hold the window titlebar 
- After click/holding the window, arrow key may be released
- Continue to hold the mouse button for a few seconds
- When mouse button is released, the player should be outside walls

**Comment by Qiangong2** [comment]
Can this be closed @bitcraft

**Comment by bitcraft** [comment]
The issue is fixed, although there still seems to be general timing glitches when window is grabbed while moving.
