### ISSUE TITLE
Moves don't reset their cooldowns after a battle ends

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1151]
If you use a move with a cooldown (such as Thunderball), and the battle ends before the cooldown finishes, the cooldown will still be in effect at the start of the next battle.

**Comment by Finnex** [comment]
I will have a look at that

**Comment by Finnex** [comment]
I wasn't able to reproduce that error. The code looks good so far. How often does it occur?

**Comment by Qiangong2** [comment]
If the last move of a battle is a move with a cooldown, the cooldown is carried over to the next battle. It happens every time that occurs

**Comment by bitcraft** [comment]
I think the problem is going to be here.  i suspect by the time the combat ends, that the player or the other trainer, etc will be out of this list.  i kinda think a better solution for this would be something like a list/set of techniques that are called during the battle, and at the end of the battle, reset them using `Technique.full_recharge()`  but you can find a different way.

![image](https://user-images.githubusercontent.com/556711/166334471-97a33c7c-3276-42ba-b3a0-efbfef14fc98.png)

**Comment by bitcraft** [comment]
i just tried the following:

* new game
* add rockitten lv 10 with cli
* start random encounter w/cli
* use thunderball
* observe that I cannot use it again
* win battle
* open new battle using random_encounter
* observe that thunderball has been reset

**Comment by bitcraft** [comment]
so for random battles, it appears that reset works as expected.  tried with trainer battles and it the cooldown was reset, too

**Comment by ultidonki** [comment]
I can't trigger this, either. 
Even if I use a cooldown attack, switch to another tuxemon, and then switch to the first one again, the cooldown has gone down or reset, as expected. 
And if I use the cooldown attack, swap to another tuxemon, then finish the battle, the cooldown still resets properly.

**Comment by JaskRendix** [comment]
Unable to trigger it too.
