### ISSUE TITLE
Trying to release a tuxemon crashes the game

### ISSUE THREAD

**Issue by rubberduck9999** [Tuxemon/Tuxemon#1188]
Trying to release a tuxemon crashes the game with the following error message (see attached image)

Also I think it is a good Idea to ask the player if he really wants to release a tuxemon, if it is not already so. I just don't know and it crashes right now

![release_1](https://user-images.githubusercontent.com/82282845/169586936-26354061-5bde-4499-9d45-1a734f556b8b.png)
![release_2](https://user-images.githubusercontent.com/82282845/169586941-2849516c-5f0f-4212-a7fd-91e2658b1270.png)

**Comment by rubberduck9999** [comment]
I tested it today and worked, so I think this can be closed now, or is there a reason it is still open?

**Comment by ultidonki** [comment]
Yes, it can be closed - I think the issue is only closed automatically, if someone puts 'Closes #xxx' or 'Fixes #xxx' in the commit message, or the title of the message you write when opening the PR in github. @daniellubovich - just to let you know you can do this for the future, as I think every Github project can do this. It's not necessary though! So yeah, this can be closed. :smiley:

**Comment by rubberduck9999** [comment]
ok, I understand, closing it now
