### ISSUE TITLE
Teleport action doesn't remove NPCs from map

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1204]
**Describe the bug**
When going from route1.tmx, to taba_town.tmx, these 8 NPC's still exist, even though they should only be in route1.tmx

If you change the event from 'teleport' to 'transition_teleport', it works, and these 8 NPC's disappear:
![route_1_weirdness](https://user-images.githubusercontent.com/89098769/176236694-1bf68338-4f2b-4aa5-9fda-5f0f0072c0c9.png)

**To Reproduce**
1. Start Tuxemon: Xero campaign, or load map taba_town.tmx
2. Continue the game until you can leave the 2nd town in the top-left of the map (or press 'N' with devtools enabled to be able to walk through walls)
3. After going to route1.tmx (you'll see the game pause for a second as you walk onto the next map), go back to taba_town.tmx, and go to the grass inbetween the first 2 villages to see all 8 NPC's from route1

**Expected behavior**
NPC's should be removed if moving between maps
(It works if you use transition_teleport instead of teleport)

**Comment by kerizane** [comment]
The issue is that the create_npc action is "leaking" into the next map and reloading the npcs. 

If you look at the object that creates them, you can see that when you enter the map the conditions are always true. This loop is running repeatedly, but you don't really notice this, because the create_npc action knows not to do anything if the npc already exists.

```
  <object id="111" name="angry populace" type="event" x="432" y="320" width="16" height="16">
   <properties>
    <property name="act10" value="create_npc omnigrunt,31,27,,stand"/>
    <property name="act11" value="create_npc omnigrunt2,32,27,,stand"/>
    <property name="act12" value="create_npc omnigrunt3,33,27,,stand"/>
    <property name="act13" value="create_npc omnigrunt4,34,27,,stand"/>
    <property name="act14" value="npc_face omnigrunt,up"/>
    <property name="act15" value="npc_face omnigrunt2,up"/>
    <property name="act16" value="npc_face omnigrunt3,up"/>
    <property name="act17" value="npc_face omnigrunt4,up"/>
    <property name="act20" value="create_npc liela,31,26,,stand"/>
    <property name="act21" value="create_npc bob,32,26,,stand"/>
    <property name="act22" value="create_npc marissa,33,26,,stand"/>
    <property name="act23" value="create_npc tuxemart_keeper,34,26,,stand"/>
    <property name="cond1" value="not variable_set letusthrough:no"/>
    <property name="cond2" value="not variable_set letusthrough:almost"/>
   </properties>
  </object>
```
The only NPCs that stay on the map are these ones, because they don't have an effective guard condition. The NPCs that have "not npc_exists" are correctly removed.

- Checks conditions
- Updates running events
- Loops over the running events and runs the actions
- Teleport action changes the map, creating a new empty running events logic
- Engine is still looping over the original events. Succeeds at creating the npc, because they aren't on the new map.

The issue is that the action creates a new object to hold the running events, but the engine is still looping over the original object.

I don't think we can make this bulletproof, as there will always be the potential for bugs relating to running_events.

1. If we don't clear the running_events immediately then we can have events running on the wrong map.
2. If we don't allow teleport whilst there are running events then this will introduce lag, or may block the teleport completely.
3. If we properly clear the running_events then there can be more complex bugs.

Imagine the following sequence:
add_monster av8r
set_variable foo
wait 5
not is_variable_set foo

If we exit the map during the wait then foo won't be set and we will be able to replay the event and get a second monster.

If we have the following sequence:
Set_variable foo
wait 5
Add_monster av8r
not is_variable_set foo

If we exit the map during the wait then foo will be set, but we won't have, and can no longer get the monster.

Obviously, this is contrived, but it seems it could happen in longer events with lots of dialogue (although I guess people should be locking the controls in this scenario).

The least surprising behaviour is probably option 1: clearing the events immediately, and that is the intended behaviour of the system.

**Comment by kerizane** [comment]
Maybe implementing teleport as a delayed teleport with delay 0 will help...

Other solutions:
- Force teleport to be the last action in the list (seems clunky)
- Have the loop check if the dict has changed / some other attribute or message to check.
- Copy the dict into a temp datastructure before looping which also gets reset.
- Grab the keys and iterate over the keys, looking up the event in the dict.
