### ISSUE TITLE
Bottom of monster sprite is cropped during start of battle animation

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1301]
Our monsters are thrown/jump into the battle. The animations are only as large as necessary for the end point of the animation  This means that for part of the animation the base of the image can be seen, and under the base is the battle background.

Ideas: 
Require back sprites to be larger (too much work).
Remove vertical overshoot in the animation.
Have the monster slide in.
Add cloud / particles to hide the glitch.

Check:
Does this affect the player sprite too?

**Comment by Sanglorian** [comment]
Good catch! I'm partial to the cloud/particles idea myself but I'd say implement whatever easiest for you at this point. Sliding in could be nice.

**Comment by kerizane** [comment]
If you can find a suitable cloud animation then we can try that.

**Comment by Sanglorian** [comment]
A couple of options:
https://wiki.tuxemon.org/File:Appearance.gif 
https://wiki.tuxemon.org/File:Breath_blue.gif

We could recolour the second one. But I like the subtlety of the first one. We could perhaps resize it so the 64x64 pixel one could go on opposing monster and a larger one on your own.

**Comment by Sanglorian** [comment]
A couple of options:
https://wiki.tuxemon.org/File:Appearance.gif 
https://wiki.tuxemon.org/File:Breath_blue.gif

We could recolour the second one. But I like the subtlety of the first one. We could perhaps resize it so the 64x64 pixel one could go on opposing monster and a larger one on your own.

**Comment by ultidonki** [comment]
I think removing the vertical overshoot is the easiest method, and adding a cloud effect can be something we add afterwards to make it look nicer. 

At the minute, the tuxemon:
1. Starts below the dialogue box (Let's call this position 0)
2. Jumps up above the dialogue box and overshoots it slightly, showing a gap (Let's call this position 1.5)
3. Falls down to the final position (which is correct) (Let's call this position 1).

Instead of going: 0 -> 1.5 -> 1
We could go: 0 -> 1 -> 0.5 -> 1

This gives the tuxemon a 'jumping out' feeling without needing too much work and without vertical overshooting. 

It's just an idea, but I think this is an easier method, although if people prefer the 'overshooting' method and want to keep it, that's fine too.

**Comment by JaskRendix** [comment]
@ultidonki @kerizane where precisely?

video: https://github.com/user-attachments/assets/ff29b840-68b1-40c0-b14c-7ef022c5c39e

**Comment by kerizane** [comment]
7 - 8 seconds.

**Comment by JaskRendix** [comment]
@ultidonki @kerizane like this?
https://github.com/user-attachments/assets/6acb6dc8-2595-4c5a-b714-b6f08354e093

**Comment by ultidonki** [comment]
Yes, that new animation looks much, much better to me! :smile:  

Thank you! 

And as I said, we can make it better in the future, with clouds or stuff, but for now that looks far better :+1:

**Comment by kerizane** [comment]
Lgtm
