### ISSUE TITLE
MainCombatMenuState behavior

### ISSUE THREAD

**Issue by ghost** [Tuxemon/Tuxemon#132]
How is the 'MainCombatMenuState' supposed to be used? 

I was trying to use multiple items in a row,(Potion,Capture Device,Potion) in that order if it matters. and i noticed that there were 2 instances of 'MainCombatMenuState' in game.active_states. Is this supposed to happen?

Here's the image i took when i found it
http://imgur.com/a/7aNnG

Their are 2 possible ways i can imagine it working.
1. The Combat menu state gets GC'd when you leave it the first time 
      --thus the need to create a new instance of it if when called again
2. The Combat menu state stays around the whole length of the battle.
      --certian functions combat modules need to account for this

I'm just trying to understand whether my problem is the state is not being GC'd correctly or if my problem is something unnecessarily creating and adding the state.

**Comment by bitcraft** [comment]
I've noticed that states do not get GC'd, and its a problem that I've put off for a while.  The current code base shares many references to things and its just complicated to get through all of it.  Someday...we'll get that particular problem taken care of.

Not being GC'd will not cause multiple instances of a particular state, however.  I haven
t noticed the multiple copies of MainCombatMenuState.  If you link your changes, I can take a look.  The order that items are displayed in a menu is controlled somewhere else entirely.

The concept is that each menu item is a sprite, and a menu can have a group that you add items to.  The actual class to layout where the items are is linked below

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/sprite.py#L314-L453

I don't actually understand what you are trying to do.  Is there a problem with how items are laid out?

**Comment by r1g1l** [comment]
The problem i'm trying to fix now is here: 
https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/states/items/__init__.py#L58-L60 

I changed the line from **_ return self.game.active_states[-1].name**   to
**_ return self.game.active_states[2].name_** ,because StartState never gets GC'd (atleast on my build it doesn't), so it is always the last item in self.game.active_states and therefor i couldn't use items the way it was.

But this function fails when there is an extra state because it returns one of the MainCombatMenuStates instead of CombatState like it should.

**Comment by bitcraft** [comment]
Yes, as the comment states, it is a bit of a hack.  The controller/state system still has some rough edges.  Please don't rely on that particular function to be there.  Actually, I'd prefer that you don't change it until we can determine if the duplicated state is a result of your changes or not.

Just for clarification, when you say "never gets GC'd", do you actually mean "not removed from state stack"?  Because that is two different things.

**Comment by r1g1l** [comment]
First to answer your question, both I've looked in bpython and its not being collected and not being removed from state stack. I suppose it doesn't matter if its not being collected as long as we remove it from the state stack?

These Were the steps i took 
1. start new game & add multiple items and monster (4 Potions,4  Capture Devices) 
2. start battle 
3. use potion
4. use capture device (it failed by the way,  I don't know if that matters)
5. used another potion 

when trying to use the last potion i got the "Item cannot be used here" message, and thought this was odd so i looked in bpython and thats how i noticed the duplicate state

**Comment by bitcraft** [comment]
Ok.  Thanks for the details.  There are a lot of issues here.  First, capture devices do not work.  Healing items, also have issues (I guess they are broke?).  So if you want to fix those, that's something to fix :smile: 

I'll open up an issue about items not working.

**Comment by bitcraft** [comment]
#148 has fixed this issue.  Verified by following steps detailed by OP.
