### ISSUE TITLE
Cannot use items

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#133]
Items are not working currently.  This issue can be closed when healing type items work in the world state (select bag from the menu) and from the combat state.  The capture device is a separate issue.

**Comment by r1g1l** [comment]
I would just like to point out healing items work as expected in and out of combat. The problem is when the item checks what state it is called from (to make sure it can be used in that state) it doesn't always return the correct state. I believe this to be the main problem.

I think other goals for this issue should be:
1. When using a healing item in combat it doesn't return to combat state it just stays
   in the item menu.
2. Add confirmation that an item is successful or failed, currently it just returns  whether it failed or not.

**Comment by bitcraft** [comment]
Thanks.  I tested items doing the following:

- Start new game
- Grab fruitera
- Start combat
- Potion doesn't work

Based on our differing experiences, it seems that the state controller will need some stress testing.

**Comment by r1g1l** [comment]
May i ask what kind of error did you get?
The "cannot use item here" dialog or an actual python error

**Comment by bitcraft** [comment]
Cannot be used here

**Comment by r1g1l** [comment]
That's what i though, upon inspection it appears that _**_state_stack**_ in core.states.state 
is not the same as _**game.active_states**_. So certain states are unable to be removed since the state engine is not aware of their presence. This is causing the issue since when an item query's game.active_states it see's more states than the state system see's. This is messing with that 'Hack' we talked about here

https://github.com/Tuxemon/Tuxemon/issues/132

Am i wrong in thinking _**_state_stack**_ and _**game.active_states**_ be equal?

**Comment by bitcraft** [comment]
Somewhat.  active_states is a "public" method that returns a list of active states.  It is used like this to prevent other classes from holding on to reference to states (and prevent them tfrom being GC'd).  Right now it is also just a copy of the stack, but in the future that may change.

**Comment by r1g1l** [comment]
Ok that makes sense. Based off that i think the solution for right now would just be making sure the states are removed from both when pop_state is called, this would fix the errors allowing items to be used, but would have to be modified later if the relationship between **_game.active_states_** and **___state_stack_** ever changes.

**Comment by bitcraft** [comment]
I think that you are not understand it completely.  active_states is not a "real variable";  It is generated from the state_stack whenever it is called.  Its a python property.  So whenever it is called, it will be whatever the stack looked like at the time.

**Comment by r1g1l** [comment]
oh that explains a lot, i'll just have to do more digging around in the state system before i try to tackle this one :)

**Comment by bitcraft** [comment]
Sounds good

**Comment by MirceaKitsune** [comment]
I believe I can confirm this: If I try to use either the Capture Device or the Potion, either in battle or in the world, I get the message "(item) cannot be used here"! I thought they simply weren't implemented, but after seeing this I realized it must be a bug.

**Comment by MirceaKitsune** [comment]
Partly fixed in latest GIT? Potions work, but capture devices still cannot be used anywhere.

**Comment by bitcraft** [comment]
Items (except capture device) seem to be reliably working again.  #148  Closing this now.
