### ISSUE TITLE
new sprites

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1536]
Since a couple of weeks I was creating new sprites, at the moment inside the sprites folders we have 2040 files (102 sprites), with this batch the number will increase to more than 200 sprites (more than 4000 files).

Since it's a massive increment, I preferred open an issue. Here: [sprites.zip](https://github.com/Tuxemon/Tuxemon/files/11250746/sprites.zip)

I attached a zip so you can check the various types. Let me know what do you think about it. Sprites involve always different hair colors, clothes, the difference depends on the single type of sprite. Nurse for instance has a bunch of new hair colors, etc.

The structure:
- beachcomber_black, beachcomber_blue, beachcomber_copper, beachcomber_fiery, beachcomber_gray
- bob_black, bob_blue, bob_fiery
- childactor_black, childactor_blonde, childactor_brown, childactor_fiery
- christie_black, christie_blue, christie_brown, christie_fiery, christie_turquoise, christie_violet
- cooldude_black, cooldude_blonde, cooldude_blue, cooldude_brown, cooldude_fiery, cooldude_red
- dragonrider_black, dragonrider_blue, dragonrider_fiery, dragonrider_green
- fashionista_black, fashionista_blue, fashionista_brown, fashionista_fiery, fashionista_red
- firefighter_blonde, firefighter_blue, firefighter_green, firefighter_w
- fisher_fiery
- florist_black, florist_blue, florist_brown, florist_fiery, florist_rose
- girl7, girl8, girl9
- granny_green, granny_red, granny_turquoise
- heroine_blonde_r
- homemaker_black, homemaker_blonde, homemaker_brown, homemaker_copper, homemaker_fiery
- magician_black, magician_blonde, magician_brown, magician_fiery, magician_grey
- nurse_blonde, nurse_blue, nurse_green, nurse_red, nurse_turquoise
- postboy_green, postboy_green_w, postboy_olive, postboy_olive_w, postboy_red, postboy_red_w
- professor_black, professor_blue, professor_brown, professor_fiery
- riverboatcaptain_black, riverboatcaptain_black_b, riverboatcaptain_blue, riverboatcaptain_copper, riverboatcaptain_fiery
- rogue_blue, rogue_copper, rogue_green, rogue_red
- scientist_black, scientist_blue, scientist_brown, scientist_fiery
- shopassist_black
- xerogrunt_green, xerogrunt_red, xerogrunt_turquoise, xerogrunt_yellow

**Comment by ultidonki** [comment]
First of all, nice work! Some of these look really good! :smiley: 

I think it was good to open this as an issue, rather than a PR. Some of these sprites, I wasn't a fan of before the recolor, so even with the new color I'm not a fan of a few of the sprites. (Sidestepping the discussion of how/when we should replace them)

I think if a modder wants to use any of these sprites, they can look through them and request the ones they want, and then you can raise a PR with just those ones in them. Otherwise there's no point adding them if they won't be used in anyone's mod, I think :smile: That's just my opinion. 

How did you recolor them all, by the way? Do you have a script, or some software? It might be useful to give modders the ability to recolor the sprites too. :smiley:

**Comment by JaskRendix** [comment]
Simply by using Gimp and a good palette (eg for hair https://www.color-hex.com/color-palettes/?keyword=hair), then there are tools in Gimp for selecting only a particular color (**select by colour tool**), once selected you replace the color by filling the selection (**Bucket fill tool** -> **fill whole selection**), but this is for the easy ones, sometimes you need to fill only similar colors. Just replace the shade with an appropriate one (light > light, dark > dark, etc) and the job is done.

It's appropriate to check also if the PNG is RGB and not indexed (all the PNGs inside the zip are RGB). To check IMAGE -> MODE (if it's indexed, check RGB). To automatize the process is better to set a keyboard shortcut (EDIT -> KEYBOARD SHORTCUTS).
