### ISSUE TITLE
Tonguespear still leeches life if it misses

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1567]
A simple issue really. The move Tonguespear should only leech life if it hits. Right now, even if it misses, it will still leech life after every turn

EDIT: aardorn uses the move

**Comment by JaskRendix** [comment]
Unaware of this mechanism and there was no sign in the previous versions (wiki included).
Because all the statuses are triggered also if the technique misses. The reason is simple:

Tonguespear and all techniques success / failure is triggered by **tech.accuracy >= random.random()** inside damage.py
Lifeleech and all statuses success / failure is triggered by **tech.potency >= random.random()** inside lifeleech.py (and respective files)

(*) this apply only to the techniques with damage (among the effects), because around 20 don't have damage.

We can remove the status (all of them or simply grabbed / lifeleech since there is a bond) if the technique misses, this would solve the problem, but this needs for someone who defines which statuses we are going to remove and which not, because if not it would result in too much hardcoding.

Consider the technique (skip), the one that appears when you cannot use any other, just tested and it triggered lifeleech too.

**Comment by Sanglorian** [comment]
Thanks for flagging! Conditions should only trigger if both accuracy and potency are triggered. E.g. an accuracy 50%, potency 50% attack does damage 50% of the time and only imposes its condition half the time that it does damage. 

Sorry for the lack of guidance. I think I posted a combat breakdown on the forum. I'm trying to track down if it still exists.

**Comment by Sanglorian** [comment]
Found them! Although things may have changed of course. If it'd be useful I can sweep through them and see what should change. https://web.archive.org/web/20210123070132/https://forum.tuxemon.org/thread.php?id=255

**Comment by JaskRendix** [comment]
Please less words, I can understand better through formulas or ifs.

`if monster.accuracy > random.random and monster.potency > random.random:`
then monster gets the condition? Is it correct?

above all, the random value, same for both?
`if monster.accuracy > 0.8 and monster.potency > 0.8:`
or not?
`if monster.accuracy > 0.8 and monster.potency > 0.5:`

I need to understand if I need to set up the random outside of the if.

**Comment by JaskRendix** [comment]
There is the PR. Shortly it fixes the issue with lifeleech, centralizes the random value and added:
`success = tech.potency >= value and tech.accuracy >= value`
to each condition / status

Do you want the same logic (lifeleech) for poison and recover too?

**Comment by Sanglorian** [comment]
Yes please, it should apply to every condition.

I'm not a programmer, but the way I think about it is:

1. Check if technique hits. Compare accuracy to random number.
2. If attack hits, check if condition(s) apply. Compare potency to random number.

So in my mind it's a property of techniques, not of the conditions themselves. But it sounds like your implementation will achieve the same effect.

**Comment by JaskRendix** [comment]
Ok, no problem regarding how they got the conditions, but regarding poison and recover still I'm not clear.

Practical example poison, same question applies to recover:
```
(Rockitten poison condition)
Cataspike hits
Rockitten hits
Rockitten loses HP due to poison
Cataspike misses
Rockitten hits
Rockitten ??? do you want Rockitten loses HP even if Cataspike misses?
```

**Comment by Sanglorian** [comment]
Once a monster has a condition,  it should keep the condition indefinitely (until something removes the condition).

So in your example Rockitten should keep losing HO even though Cataspike missed.

Thanks for checking, good thinking with the example.

**Comment by JaskRendix** [comment]
Perfect, I'm rewriting the PR schematically, so it's easy to understand.

**Comment by JaskRendix** [comment]
Ok, I was able to solve the failure bug of special range techniques (boulder, hibernate, etc), the animation bug (the animation of boulder wasn't shown) and the tackle bug (the monster was still, no movement).

**Comment by JaskRendix** [comment]
Look, I think we are ok. Let me know if you're ok.

I was able to solve the failure bug of special range techniques (boulder, hibernate, etc), the animation bug (the animation of boulder wasn't shown) and the tackle bug (the monster was still, no movement). Now when eg Rockitten uses boulder it moves, the animation is shown and the tech can hit or miss as any other techs, obviously without damages.

added the check if the target or user monster have more than 0 HP;
excluded items (before if you used a potion, then the monster leeched, now not anymore);
excluded skip (when you skip move, the monster don't leech);

**Comment by Sanglorian** [comment]
Thanks for fixing those bugs.

But in terms of leechlife, I think it should happen once per turn regardless of what the monster who is being leeched does. So if Aardart uses Tonguespear on Nudiflot, then at the end of the turn Nudiflot is leeched. And the end of the next turn, and so on, even if Nudiflot skips or uses a potion.

**Comment by JaskRendix** [comment]
let me understand, because I'm confused.

The situation after the PR
```
aardorn vs rockitten (rockitten condition lifeleech)
- aardorn will get HP only if the attack is successful
- rockitten will keep losing HP no matter if aardorn hits or misses or uses an item or skips
```
Is it correct?

**Comment by Sanglorian** [comment]
No sorry, Aardorn will get HP regardless of whether the attack hits or misses. And either way, it happens at the end of the turn.

So imagining a new fight, Aardorn vs Rockitten.

Aardorn uses Tonguespear. It has an 80% chance to hit. It hits. Because it hit, it has 100% chance to impose leechlife.

Rockitten uses Thunderball. ...

End of turn: Rockitten loses 1/16th of its maximum HP. Aardorn heals that amount.

Next round: 

Aardorn uses Acid. It has a 40% chance to hit. It misses.

Rockitten uses Thunderball. ...

End of turn: Rockitten loses 1/16th of its maximum HP. Aardorn heals that amount.

**Comment by JaskRendix** [comment]
Well, ok
