### ISSUE TITLE
Dialog ends at a comma

### ISSUE THREAD

**Issue by josepharaoh99** [Tuxemon/Tuxemon#168]
Okay, a weird issue here. It's not that big of a deal, but if it's not fixed, it could cause issues in the future.

So, I was working on the Tuxemon map, and I was making events for the part where you're stopped if you try to leave town without a starter. I made the following event:

    act1 dialog_chain Wait, You can't leave town without a starter!
    act2 dialog_chain But I know where you can get one! Follow me!
    act3 dialog_chain ${{end}}
    act4 set_variable cant_leave_starter_town_yet:true
    act5 set_variable guard1_walk_to_mart:true
    cond1 is player_at 32,0
    cond2 not variable_set talked_to_assistant_junkyard:true
    cond3 not variable_set cant_leave_starter_town_yet:true

And guess what the first dialog said:
  Wait
That's all, and it was kind of strange. So I changed act1 to
    `    act1 dialog_chain Wait! You can't leave town without a starter!`
and it displayed exactly what I wanted. So, why is the dialog ending at a comma? Any help?

**Comment by xirsoi** [comment]
Wrap the line in quotes, like this
```
act1 dialog_chain "Wait, You can't leave town without a starter!"
```

**Comment by ShadowApex** [comment]
As xirsoi said, the event engine uses commas to separate the event's parameters. If you want to include a comma in your dialog, you can do so by "escaping" the comma with a `\` character like this:

```act1 dialog_chain Wait\, you can't leave town without a starter!```

The code that splits up the event parameters is located in the map parser in `core.components.map`, which can also be viewed [here](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/map.py#L594).

With that said, you actually should try and use the [`translated_dialog_chain`](https://github.com/Tuxemon/Tuxemon/wiki/event-reference#translated_dialog_chain) action instead of `dialog_chain`, so the campaign can support multiple languages/locales. When you use the translated dialogs, you won't need to worry about escaping commas.

To use `translated_dialog_chain` you would need to also edit [resources/db/locale/en_US.json](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/resources/db/locale/en_US.json) and add all your dialog there with an identifier (also called a "slug"). Here's an example of how you could use the translated dialog chain action:

**resources/db/locale/en_US.json**

```json
{
    "map_route0_dialog1": "Wait, you can't leave town without a starter!",
    "map_route0_dialog2": "But I know where you can get one! Follow me!",
   ...
}
```

**Map Action**

```
act1 translated_dialog_chain map_route0_dialog1
act2 translated_dialog_chain map_route0_dialog2
act3 translated_dialog_chain ${{end}} 
```
