### ISSUE TITLE
The move "All In" does damage even if it misses

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#1680]
Just what the title says. If an opposing tuxemon uses "All In", it still damages the player's tuxemon, even if it misses. I've observed it happening with Chloragon specifically, but it could affect all tuxemon.

**Comment by JaskRendix** [comment]
After some mass testing, it wasn't an issue of All_In technique only, the real issue was the effect recover, so all the techniques with the effect were affected.

Thanks, because it was something I missed, it'll help me to fix a couple of more bugs (it could happen the same with poison and lifeleech too).

Probably is going to fix #1673 too.
