### ISSUE TITLE
Automatic targeting of techniques when there is only one eligible target

### ISSUE THREAD

**Issue by Sanglorian** [Tuxemon/Tuxemon#1804]
First of all, I wanted to say that I'm thrilled to be playing Tuxemon with so many developments since the last time I played. Because it's been a while, I have a lot of thoughts which I'll share over the coming days -- but that doesn't diminish how chuffed I am to see it come alive. 

**Is your feature request related to a problem? Please describe.**
In combat, when you select a technique which can target an enemy, it shows the cursor and requires you to accept even if there's only one eligible target. 

**Describe the solution you'd like**
In these circumstances (which should occur for most if not all techniques in 1 vs 1 battles), it could automatically select the only eligible target and skip this stage. It is good to have the option for 2 vs 2 battles though. 

(This could also apply to items. Many items, like the ones you use on your team, have multiple options for targets. But in a 1 vs 1 battle, a tuxeball's only eligible target is the opponent monster, for example).

**Comment by DavidLiang1129** [comment]
I'm also very happy, I'm a former Pokemon Hacker, I didn't like the relatively popular tool (I don't want to name them) because it was too complicated for me, so I translated an old tool that was relatively easy to use, but not many people liked it, one person even obviously called me an idiot, And then I got fed up, and I started to realize that I was doing something wrong in some way, so I started looking for open source clones of Pokemon and stuff like that, and then I found Tuxemon, and I couldn't wait to translate it into Chinese and finally did it, and I'm still making my own games based on Tuxemon, and I'm like, I really enjoyed meeting you guys, I love Tuxemon!

**Comment by JaskRendix** [comment]
Related to #1176 and it needs to be completely redone. I'm referring to:
```
  "target": {
    "enemy monster": 0,
    "enemy team": 0,
    "enemy trainer": 0,
    "item": 0,
    "own monster": 0,
    "own team": 0,
    "own trainer": 0
  },
```
regarding the damaging (like enemy team and trainer) can be defined in damage.py effect (technique) with an existing parameter called is_area.
