### ISSUE TITLE
Error when speaking to the nurse and say "Yes" to heal Tuxemon when having none

### ISSUE THREAD

**Issue by blackscorpionster** [Tuxemon/Tuxemon#1842]
This happened after talking to Professor Tuxemon in the shop and rather than going with him to see the second announcement, I went to the hospital and talked to the nurse.

Traceback (most recent call last):
  File "run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/litza/Dev/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/litza/Dev/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/home/litza/Dev/Tuxemon/tuxemon/client.py", line 370, in update
    self.event_engine.update(time_delta)
  File "/home/litza/Dev/Tuxemon/tuxemon/event/eventengine.py", line 365, in update
    self.update_running_events(dt)
  File "/home/litza/Dev/Tuxemon/tuxemon/event/eventengine.py", line 458, in update_running_events
    action.start()
  File "/home/litza/Dev/Tuxemon/tuxemon/event/actions/variable_math.py", line 53, in start
    operand1 = number_or_variable(self.session, var)
  File "/home/litza/Dev/Tuxemon/tuxemon/tools.py", line 250, in number_or_variable
    raise ValueError(f"invalid number or game variable {value}")
ValueError: invalid number or game variable cathedral_ads

**Comment by JaskRendix** [comment]
Thanks for reporting, I'm going to set up a block if someone without monsters tries to heal monsters.

**Comment by toia77** [comment]
@kerizane  @JaskRendix 

It's not really fixed. As of today it still crasses (invalid number or game variable cathedral_ads). I guess it may be because this cathedral_ads thing is not set up as expected.
I tried saving the game and loading, so I didn't have to pass through the whole intro. But in that scenario the bug is fixed because of lines 63 to 64 in saver_upgrader.py

```
    if "cathedral_ads" not in save_data["game_variables"]:
        save_data["game_variables"]["cathedral_ads"] = 0
```

I've searched for the cathedral_ads string in the project files, and found it (among other places) in file 
`./Tuxemon/mods/tuxemon/maps/healing_center.tmx

    <property name="act25" value="variable_math cathedral_ads,+,1"/>
    <property name="act4" value="variable_math cathedral_ads,+,1"/>
`
I guess this sort of variables should be initialized somewhere (i.e. how it's being done in saver_upgrader.py). But provided I guess that a tmx file may have any arbitrary variable name inside, a strong solution should be implemented (my guess, if a variable does not exist when calling variable_math.py, create it... I don't know if it actually makes sense).

Best regards,
   Carles.
