### ISSUE TITLE
Game crashes when Aardorn learns Skip

### ISSUE THREAD

**Issue by janWilejan** [Tuxemon/Tuxemon#1983]
**Describe the bug**
Game crashes when Aardorn learns Skip

**To Reproduce**
1. Aardorn learns skip
2. Go to Aardorn > Techniques
3. Game crashes

**Expected behavior**
Game doesn't crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu 20.10, Windows 10]
 - Python Version [e.g. 22]

**Additional context**
Github won't let me submit a PR for some reason. I wrote a fix for the crash: https://github.com/janWilejan/Tuxemon/commit/3abb83350b667fd4b05a896db4fcf376d1de429d

**Comment by Grimmys** [comment]
@janWilejan you cannot sumbit a PR because it looks like your repository is not a fork of this one.

If you want to do things properly, you need to click on the "Fork" button at the top of the main page of this repository.
Then just redo the same steps as you did before (clone, new branch, introduce changes, push), and you should be able to create the PR.
