### ISSUE TITLE
Crash when using Boulder attack with Rockitten

### ISSUE THREAD

**Issue by me-self** [Tuxemon/Tuxemon#1989]
**Describe the bug**
A crash when using Rockitten's boulder move

**To Reproduce**
1. Start a battle with Rockitten
2. Use the `Boulder` attack

**Expected behavior**
The attack takes place as with any other attack, and the game continues as usual.

**Screenshots**
![Screenshot from 2023-08-18 18-52-36](https://github.com/Tuxemon/Tuxemon/assets/115949508/f2a9ff23-5bf0-48d7-a84c-6f483d363c59)

**Desktop (please complete the following information):**
 - OS: Vanilla OS
 - Python Version: Python 3.10.7

**Additional context**
 - This error occurs in the the Flatpak package
 - the issue appears to be a case of invalid argument count for this move's function:
 `TypeError: Technique.hardshell() takes 2 positional arguments but 3 were given`

**Comment by Grimmys** [comment]
I tried but cannot reproduce the issue, the technique is working fine on my side.

Also, `Techinque.hardshell` is not something that can be find anymore in the code source.
It looks like it was indeed a method before this commit: [6cce3c86caf282a8856248ac2513c31f12ed520b](https://github.com/Grimmys/Tuxemon/commit/6cce3c86caf282a8856248ac2513c31f12ed520b), that was pushed in 2022.

I'm assuming your are just using a very old build (the latest release maybe?) and the issue is already fixed.

**Comment by me-self** [comment]
Are you using the flatpak from flathub?
Yeah, the flathub flatpak was last updated... `Changes in version 0.4.34
about 1 year ago`

**Comment by freshreplicant** [comment]
As far as I know the flatpak should update with the next release, so #1928 is technically related here. @Murmele may be able to confirm.

**Comment by Murmele** [comment]
@freshreplicant yes exactly the flathub manifest will be updated to a new version once a new release was created

**Comment by Murmele** [comment]
Is it reproducable with the nightly: https://github.com/Tuxemon/Tuxemon/releases/tag/latest ?

**Comment by Grimmys** [comment]
All depends on whether the flatpack from the nightly is indeed taking build from 2 days ago or from 2 years ago.

For this kind of issue related to outdated build, we could be logging in the console at the start up of the game the git hash of the latest commit, and then add it as a field in the "bug issue template".
So we could more easily spot on which game version the bug is reproducible.

**Comment by me-self** [comment]
> All depends on whether the flatpack from the nightly is indeed taking build from 2 days ago or from 2 years ago.
> 
> For this kind of issue related to outdated build, we could be logging in the console at the start up of the game the git hash of the latest commit, and then add it as a field in the "bug issue template". So we could more easily spot on which game version the bug is reproducible.

Okay, so I can confirm that the nightly flatpak is at a newer state than the one on flathub. As for if the bug is still present I'll need to complete the tutorial to test because I can't load my save :/

**Comment by Murmele** [comment]
> All depends on whether the flatpack from the nightly is indeed taking build from 2 days ago or from 2 years ago.
> 
> For this kind of issue related to outdated build, we could be logging in the console at the start up of the game the git hash of the latest commit, and then add it as a field in the "bug issue template". So we could more easily spot on which game version the bug is reproducible.

Yes and maybe adding a question if the nightly version was tested and if the bug is fixed there. Then linking to the url, so the issue reporter can directly download and testing it

**Comment by me-self** [comment]
I'll close this issue as it's not present in the current version, that being said, the flatpak distributed on flathub should be updated.
