### ISSUE TITLE
I found 70+ 8-bit JRPG music!

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#2022]
First of all, long time no see everyone, sorry I haven't contributed to Tuxemon in a long time, to be honest, I found Tuxemon music a bit lacking, so I looked for some music a while back (see #1833), and now, again, I found some music on OpenGameArt, Using the CC-BY 4.0 license, I downloaded and listened to some, and personally felt pretty good.

Link:
https://opengameart.org/content/full-8-bit-jrpg-soundtrack-downloadable-and-editable-music-pack

I hope you enjoy it!

**Comment by bitcraft** [comment]
great find!

**Comment by Sanglorian** [comment]
Cool! Very happy for someone to replace any music in the Spyder storyline with other stuff they think is suitable.

**Comment by Davidliang11292** [comment]
Sorry everyone, I am the original DavidLiang1129, due to some negligence (I formatted the phone because the phone started to run slowly, originally I thought there would be no problem, but the backup program did not backup the token) accidentally lost the 2FA token, I can only register a new account, if anyone wants to verify that I am myself, You can send me an email.

**Comment by Davidliang11292** [comment]
![IMG_20231209_201747.jpg](https://github.com/Tuxemon/Tuxemon/assets/152856832/f9fdc615-6f98-4f71-8aa4-3d3f0deb7296)

**Comment by Grimmys** [comment]
It's ok, I guess we can trust you.

It's not like if there was anything sensitive in play anyway 👍

**Comment by Davidliang11292** [comment]
> It's ok, I guess we can trust you.
> 
> It's not like if there was anything sensitive in play anyway 👍 

Thanks!
