### ISSUE TITLE
Protagonist should jump obstacles 

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#221]
Protagonist should be able to jump obstacles, not walking through them.
This means that this situation is not valid
![schermata da 2016-08-21 14-09-20](https://cloud.githubusercontent.com/assets/139841/17837078/e3114212-67a8-11e6-9340-be979fd9c1c7.png)

**Comment by xirsoi** [comment]
We'd need to label a tile as a jumpable ledge and indicate from which direction it can be jumped. This would be pretty easy to do after that, I think.

**Comment by bitcraft** [comment]
Agreed.  I think we'll need some special handling of this case for a jumping animation of some sort.

**Comment by MirceaKitsune** [comment]
👍 for this idea. Since actual jumping (a full jump animation with > 1 tile movement) might be harder, I would invoke #264 in the meantime, which would offer an easier solution until this is possible: My suggestion is about allowing tiles to force the player to keep walking, which will be needed separately for conveyor belts and possibly other special cases. Ledges could use it for now in order to prevent the player from being able to sit in the middle.

**Comment by MirceaKitsune** [comment]
With forced movement now implemented, I believe this should be okay to close. Unless the issue also refers to having a jumping sound and potentially a more complex jump animation, though from what I'm seeing it was about the capability to keep walking over ledges which we have now.
