### ISSUE TITLE
If a Tuxemon has too many techniques, the game will crash

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#2284]
When your Tuxemon gains enough levels to learn more than four moves, the game will crash with the following error:

```
[2024-02-25 19:52:16,615] tuxemon.event.actions.get_monster_tech - ERROR - Game variable check_moves not found
Traceback (most recent call last):
  File "C:\Users\Kurt\Downloads\Tuxemon\run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\main.py", line 90, in main
    client.main()
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\client.py", line 301, in main
    update(clock_tick)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\client.py", line 346, in update
    self.event_engine.update(time_delta)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\eventengine.py", line 359, in update
    self.update_running_events(dt)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\eventengine.py", line 450, in update_running_events
    action.start()
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\actions\remove_tech.py", line 44, in start
    tech_id = uuid.UUID(player.game_variables[self.tech_id])
  File "C:\Users\Kurt\AppData\Local\Programs\Python\Python310\lib\uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

**Comment by JaskRendix** [comment]
Fixed, I checked your **taba-battle-area-4** branch and I would suggest you these changes:
- remove `<property name="act23" value="set_variable battle_last_result:check"/>`, since **battle_last_result** will be automatically overwritten at the end of the battle (you can find it in **taba_ba_br_2.tmx** and **taba_ba_br_4.tmx**);
- replace `<property name="cond2" value="is variable_set battle_last_result:lost"/>` with `<property name="cond2" value="not variable_set battle_last_result:won"/>` (note the NOT in front of variable_set, this because in the remove scenario of a draw the game doesn't get stuck), it appears both in **taba_ba_br_2.tmx** and **taba_ba_br_4.tmx**;
- remember that you can set a time in `<property name="act5" value="teleport_faint"/>` to avoid to be abruptly teleported (requested by yourself on Discord a couple of months ago);

**Comment by JaskRendix** [comment]
Fixed @Qiangong2  . I checked your **taba-battle-area-4** branch and I would suggest you these changes:
- remove `<property name="act23" value="set_variable battle_last_result:check"/>`, since **battle_last_result** will be automatically overwritten at the end of the battle (you can find it in **taba_ba_br_2.tmx** and **taba_ba_br_4.tmx**);
- replace `<property name="cond2" value="is variable_set battle_last_result:lost"/>` with `<property name="cond2" value="not variable_set battle_last_result:won"/>` (note the NOT in front of variable_set, this because in the remote possibility of a draw - both lose - the game doesn't get stuck), it appears in **professor_lab.tmx**, **taba_ba_br_2.tmx** and **taba_ba_br_4.tmx**;
- remember that you can set a time in `<property name="act5" value="teleport_faint"/>` to avoid to be abruptly teleported (requested by yourself on Discord a couple of months ago);
- eventually you can set a different background for the battles (instead of the default grass) with this event action (see below);

```
   <properties>
    <property name="act1" value="set_variable environment:interior"/>
    <property name="cond1" value="not variable_set environment:interior"/>
   </properties>
```
just replace **interior** with anything you find interesting [here](https://wiki.tuxemon.org/Battle_Terrain)  (eg. **bridge**, etc.), you just need to add it once in **taba_ba_main.tmx** (or in the specific map where there is **start_battle** if you want to modify it every time);
