### ISSUE TITLE
The game crashed when entering the building.

### ISSUE THREAD

**Issue by Davidliang11292** [Tuxemon/Tuxemon#2304]
**Describe the bug**
I loaded one of my saves, but the game crashed when I entered the building.
**To Reproduce**
1. Started a new game.
2. Saved the progress near a building.
3. Exited and re-entered the game.
4. Loaded the save and attempted to enter the building.
5. The game crashed.

**Expected behavior**
The game should not crash; instead, it should continue to run smoothly.

**Screenshots**
![捕获.PNG](https://github.com/Tuxemon/Tuxemon/assets/152856832/2bd72fcd-32f6-4ed8-b976-f69f1a0d3c89)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Python Version 3.12.2

**Additional context**
If before entering the building, I navigate to another outdoor scene and then return, upon re-entering the building, the game does not crash.

**Comment by JaskRendix** [comment]
Which scenario? Which map? Which building?

**Comment by Davidliang11292** [comment]
> Which scenario? Which map? Which building?

Any building on any map

**Comment by Davidliang11292** [comment]
I recorded a video:
https://github.com/Tuxemon/Tuxemon/assets/152856832/896c591b-a4b5-47f6-957b-dc5987fe77b1

**Comment by ultidonki** [comment]
I've confirmed this happens - BUT you have to save in the exact same position as shown in @Davidliang11292 's video. If you save eg. outside of the Healing Center, you can enter buildings fine after loading. I've only managed to replicate it when saving outside the mart in spyder_cotton_town.tmx, when I tried it in a few other maps I couldn't replicate it. 

This is both with a Tuxemon, and without any tuxemon (teleporting straight to the map, saving and then re-loading). 
I have a save file that doesn't work, but I can't see what the issue is, comparing it to a save file that works. I don't see any references to co-ordinates or anything in the save file. 

Here's the save file, just in case anyone doesn't believe it won't work, or can't replicate it: If you load it, then go into any building, it'll crash with a similar error to the one @Davidliang11292 posted earlier.
[slot2.zip](https://github.com/Tuxemon/Tuxemon/files/15341590/slot2.zip)

**Comment by Davidliang11292** [comment]
> I've confirmed this happens - BUT you have to save in the exact same position as shown in @Davidliang11292 's video. If you save eg. outside of the Healing Center, you can enter buildings fine after loading. I've only managed to replicate it when saving outside the mart in spyder_cotton_town.tmx, when I tried it in a few other maps I couldn't replicate it. 
> 
> This is both with a Tuxemon, and without any tuxemon (teleporting straight to the map, saving and then re-loading). 
> I have a save file that doesn't work, but I can't see what the issue is, comparing it to a save file that works. I don't see any references to co-ordinates or anything in the save file. 
> 
> Here's the save file, just in case anyone doesn't believe it won't work, or can't replicate it: If you load it, then go into any building, it'll crash with a similar error to the one @Davidliang11292 posted earlier.
> [slot2.zip](https://github.com/Tuxemon/Tuxemon/files/15341590/slot2.zip)
> 

Thank you! I wrote a story outline the other day, do you have any suggestions/comments? (Sorry this might be a bit off topic)
