### ISSUE TITLE
[Question] "Tuxemon took poison damage"

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#236]
I see in [translation file](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/resources/db/locale/en_US.json) that there are many keys about damages:

```
    "combat_state_poison_damage": "${{name}} took poison damage!",
    "combat_status_damage": "${{name}} took ${{status}} damage!",
    "status_faint_name": "Faint",
    "status_poison_name": "Poison",
```

When you play and get poisoned, the game shows a message combining "combat_status_damage" and "status_poison_name" as you can see in the screenshot below.

![schermata da 2016-08-26 14-07-06](https://cloud.githubusercontent.com/assets/139841/18005010/a64af07e-6b97-11e6-98f8-afb11169b0a0.png)

If so:

- Italian translation should be adapted
- Why there is "combat_state_poison_damage"?
- When "status_faint_name"  is used?

**Comment by bitcraft** [comment]
> Why there is "combat_state_poison_damage"?

The "took status damage" is a placeholder for status effects that don't get translated right away.  Because we just have one status effect, poison, there hasn't been any real motivation to get a standard message.  Hope that helps.  The translation/localization has been a bit chaotic.

> When "status_faint_name" is used?

It may eventually be used in the monster info screen.  #4

**Comment by Airon90** [comment]
Ok, thank you very much!
