### ISSUE TITLE
If you put all your surviving monsters in a kennel, the game thinks you've been defeated

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2464]
**Describe the bug**
If you have 2 defeated tuxemon, and 1 tuxemon still alive.
If you put the tuxemon that's still alive in the kennel, the game thinks you've been defeated, and calls teleport_faint to your nearest health center. 

**To Reproduce**
Here's a save file: 2 tuxemon are defeated, and Botbot still has a few HP.
[slot1_candy_health_center.zip](https://github.com/user-attachments/files/17105020/slot1_candy_health_center.zip)
Put 'Botbot' in the kennel, and you will be teleported to the previous health center.

Well, it's not the biggest problem, just a bit strange. When your tuxemon are in quarantine, you have to take some tuxemon out of the kennel. When I took out one of my tuxemon (which was defeated when I put it in the kennel) I was surprised to be teleported to the health center of the previous town. You can come back using the Shipmaster (if you've saved him) but otherwise you'd need to walk through the route b/6 again.

**Comment by JaskRendix** [comment]
It's weird that the kennel only checks the number of monsters in your party, so we just need to tweak it to account for the faint ones too. I'll take care of that part.

My only concern is setting things up for Spyder, since it's the only one with that 'omniscient' teleporting feature. I remember some people complained about duplicate code in the maps back when we had the old teleport_faint system. In hindsight, it might have been better to use NPCs to block access to certain maps, but I'm guessing that would have led to the same complaints about duplicate code.
