### ISSUE TITLE
Make it more obvious when you've completed the Spyder campaign

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2492]
After you complete the Spyder campaign, it's not obvious that you've completed it, and there's no story left to play.

I really like the ending so far, but after talking to the guy on the radio:
1. You walk down and Billie and Scoop guy are there, but they don't say anything if you try to talk to them.
2. As a player, I'm wondering if there's any more gameplay, or if that's the actual ending?
Some sort of 'The end!' screen or something (maybe I'll draw an illustration?) or epilogue, or some thing to tell the player "It's finished"? 
@Sanglorian Do you have any ideas?

Here's a save file just before the ending: Just walk up and fight the final boss. 
[slot2_just_before_ending.zip](https://github.com/user-attachments/files/17267611/slot2_just_before_ending.zip)

**Comment by JaskRendix** [comment]
There's definitely more to explore and do in the game, but the main story is wrapped up. That's why I've been focusing on the flashbacks. Hey, have you seen #2482 ? You'll need to use the PC to tackle the next one. I'm actually thinking about adding even more stuff to the game, but I haven't heard back from you yet, even though I tagged you.

I was thinking it would be awesome to create an illustration that wraps up the Spyder campaign, but I don't just want to stop at the ending. I think it would be really cool to create a piece that we could use at the start of the campaign too, maybe even as a background image. That way, we could replace the current 'new game' choice with something more visually appealing. Of course, that would mean we'd need to create a similar artwork for the Xero campaign as well. What do you think? Would you be up for creating some illustrations to help bring this idea to life?

This is the standard dimension for the background: [background](https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/gfx/ui/background/gradient_blue.png)

I've been experimenting with a new state that's similar to the ending credits, but I still have a few things to iron out before I can implement it.

**Comment by Sanglorian** [comment]
> There's definitely more to explore and do in the game, but the main story is wrapped up. That's why I've been focusing on the flashbacks. Hey, have you seen #2482 ? You'll need to use the PC to tackle the next one. I'm actually thinking about adding even more stuff to the game, but I haven't heard back from you yet, even though I tagged you.
> 
> I was thinking it would be awesome to create an illustration that wraps up the Spyder campaign, but I don't just want to stop at the ending. I think it would be really cool to create a piece that we could use at the start of the campaign too, maybe even as a background image. That way, we could replace the current 'new game' choice with something more visually appealing. Of course, that would mean we'd need to create a similar artwork for the Xero campaign as well. What do you think? Would you be up for creating some illustrations to help bring this idea to life?
> 
> This is the standard dimension for the background: [background](https://github.com/Tuxemon/Tuxemon/blob/development/mods/tuxemon/gfx/ui/background/gradient_blue.png)
> 
> I've been experimenting with a new state that's similar to the ending credits, but I still have a few things to iron out before I can implement it.

An opening image to advertise the Spyder campaign, and another when the "main" campaign is done would be lovely - if you had the time and interest, @ultidonki . Good idea @JaskRendix ! I agree it's nice to flag to the player that the "main" game is done.
