### ISSUE TITLE
Map music doesn't resume playing after battle

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#267]
After exiting a battle, the map music doesn't resume playing, and you only get silence. You have to enter another map and go back in order to hear the ambient song again.

As always, I'm using the development branch. Clarifying this as @ShadowApex said this should have been fixed on this branch, but I get the problem with the latest commit on it.

**Comment by dulsi** [comment]
My fix for this bug is a quick fix. I would prefer to see the mixer and current_music objects combined. That way we ensure that what we think is playing really is. The start_battle function for example didn't set current_music["song"] so the system would think a different song is playing than the one that actually is.

**Comment by bitcraft** [comment]
Awesome, seems to be fixed now.  @dulsi Does everything work now?

**Comment by dulsi** [comment]
Yes. Everything works now.
