### ISSUE TITLE
EDIT: comma problem

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#286]

**Comment by Qiangong2** [comment]
Edit: the game also crashes if the line of text wraps to a new line

**Comment by ShadowApex** [comment]
Thanks for reporting this! The reason a comma stops dialog is because the event system looks for commas to look for the parameters of an action. Some actions, like [teleport](https://github.com/Tuxemon/Tuxemon/wiki/event-reference#teleport), need 3 parameters (the map, x position, and y position).

To prevent this, you should be able to use `\,` instead of `,` in your dialog. If the comma has a backslash before it, it shouldn't interpret it as a separate argument. Let me know if you still have this issue even when using a backslash.
