### ISSUE TITLE
[Android] All touch events send a K_UP event for all buttons

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#30]
Currently in the Android build, any button you touch (d-pad, a or b buttons), will trigger a K_UP for all other buttons. This causes all button press conditions to be true, regardless of what button you press.

**Comment by HugopGhost** [comment]
I was about to post  an issue here but it seems related to this one. If you don't mind, I am going to repost it here because it has a question on note 1.

---------------------------------------------------------------

The controllers don't work/are ignored everywhere except on levels. On the start screen, I can't scroll down to "Continue" or on battle scenes, I can't run away because no matter where I click, the entire screen is "A".

Note: When I click "B", the start menu opens. If I don't have a Tuxemon, I can go down to "TUXEMON" and then no matter where I click, I can open it and see my empty list. When I have a Tuxemon, the entire screen becomes "A" but a random Tuxemon appears. Is that a bug or a testing feature?

Note 2: When I keep trying, I manage to click "Up" and go to the Menu bar "EXIT" but 2-5second laters, it crashes.

**Comment by bitcraft** [comment]
Maybe @ShadowApex knows this, but when I test on PC by enabling the controller overlay, everything seems fine.  Is the main difference on android that the overlay is enabled or not?  Any way to test this behavior on PC?

**Comment by ShadowApex** [comment]
> Maybe @ShadowApex knows this, but when I test on PC by enabling the controller overlay, everything seems fine. Is the main difference on android that the overlay is enabled or not? Any way to test this behavior on PC?

Yeah, the main difference is that the controller overlay is on. You can view the manual Android build instructions [here](https://tuxemon.org/android-install.html) on the Tuxemon website that I use for Android builds. For some reason the bug only appears on the Android build and doesn't manifest when you try the controller overlay on PC. I still need to try and enable some logging to find out what's happening on Android specifically.

**Comment by Qiangong2** [comment]
Is this still an issue?

**Comment by bitcraft** [comment]
No recent android build, hasn't been tested.

**Comment by bitcraft** [comment]
obsolete
