### ISSUE TITLE
NPC Movement

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#320]
Would it be possible to create an action that calls a file that says what tiles an npc should move?

something like `npc_move npc_name,move file, speed (s)`

**Comment by bitcraft** [comment]
Have you tried the pathfind action?  Does that work for you?  Or you want to script exact movements?

**Comment by Qiangong2** [comment]
@bitcraft 

pathfind just teleports the npc, I want it to look like they are walking up to something, or running away. That's where the speed would come in.

**Comment by bitcraft** [comment]
Just an update, I am currently working on this issue....among others.

**Comment by Qiangong2** [comment]
okay, thanks. I haven't been working on Tuxemon too much lately as my laptop broke and now I am stuck on my Surface 2 RT. If Tiled could get ported, I'd be able to work again, I'm looking into that now.

**Comment by MirceaKitsune** [comment]
Does this include NPC wandering around? I believe that was one of the important missing basics, been curious if it might be addressed too.

**Comment by bitcraft** [comment]
@MirceaKitsune I'll see if I can test that while I'm working on this.

**Comment by Qiangong2** [comment]
Any update on this @bitcraft ?

**Comment by bitcraft** [comment]
Sorry, Just ending the busy season at work.  I have not recently had time for anything besides family and day jobs.  I hope to check out things like this soon.  I remember starting it, but there were some odd issues that made it not an easy fix.

**Comment by bitcraft** [comment]
I just had a thought about this.  Since movement is tile based, what if we condensed the movement definition to a simple string of the following letters: U D L R  (up, down left, right).

For example, to move two spaces to the left just do "LL".  or a move complex "LLDLDRRRU"?

@ShadowApex @MirceaKitsune

**Comment by xirsoi** [comment]
That sounds downright elegant to me. Simple, straightforward, expressive 👍

**Comment by MirceaKitsune** [comment]
@ShadowApex That looks pretty okay. Though I still wonder if it might be easier to do this similarly to OHRRPGCE, and instead have a chain of commands telling the NPC where to move each time:

`npc_move_by_x -5,10 # move 5 units in direction -X at speed 10`
`npc_move_by_y 3,8 # move 3 units in direction +Y at speed 8`
`npc_move_to_x 120,5 #move to tile 120 in direction X at speed 5`
`npc_move_to_y 67,5 # move to tile 67 in direction Y at speed 5`

Also I wonder if NPC wandering might best be implemented using a similar command too:

`npc_wander 0 # disable wandering`
`npc_wander 5,1,3,10 # enable wandering: walk starting frequency, walk stopping frequency, turning frequency, walk speed`

**Comment by bitcraft** [comment]
I'd like to keep the 'wander' command out of this thread.  The "to" and "by" modifiers are good to keep in mind.

**Comment by Qiangong2** [comment]
I feel like @MirceaKitsune suggestion needlessly adds more actions than needed. We aren't dealing with huge maps on Tuxemon, so far the biggest map seems to be the route1 map immediately after the starting map and that one isn't too large. I think the LLUURDL... etc. idea is the better of the two

**Comment by MirceaKitsune** [comment]
@Qiangong2 We can't know how big the maps people make may be: If you need a NPC to preform complex movements over a large area, the string may get pretty big and messy. Of course there's also the option of going for an in-between solution:

`npc_move U 5 10,L 3 10,D 1 8,R 5 6`

In this case, commas are used to separate actions whereas spaces are used to separate the parameters of each action (direction, tiles, speed). For instance "U 1 10,R 2 5" means "go up 1 tile at speed 10, then go right 2 tiles at speed 5".

There are a lot of advantages to this approach: Firstly the speed is customizable per move, so you can make a NPC run to a corner then slow down and proceed calmly. Further more, by specifying 0 tiles you can make the NPC only turn in that direction without moving there. We can even add pausing this way, so for instance "D 0 10" means "look down then pause for 10 ticks". This would make very efficient use of all 3 parameters, and can also be supported for players to do proper cutscenes!

@bitcraft and @ShadowApex what do you think of this idea?

**Comment by bitcraft** [comment]
I think I would prefer to separate look/facing and move actions, instead of creating complex actions which combine functionality.  Actions are no longer required to execute in one frame, so you can treat it like a script.  So there is no need to try to fit moving, facing, and waiting in one command.

The following would work as expected, over several frames:
```
npc_move ....
npc_look down
wait 10
npc_move ...
npc_move ...
wait 10
npc_look left

...etc...
```

It would also be possible to have a "set movement speed" action, to further reduce the complexity of each action.  I'm not saying that should happen for sure, but it is something to think about.

I like the suggestion about implementing strafing.  Currently, it is not possible because npcs will always face the direction they are moving, but I am working to separate them in my "npc movement & pathfinding" PR (in the works).

**Comment by MirceaKitsune** [comment]
Fair enough. My suggestion is a bit more complex, but crams up a bit of extra functionality in one line while offering more flexibility. A simple letter list like "LLLUURUDD" doesn't let you specify the speed of each movement nor the look direction to allow strafing or walking backwards, whereas something of the form "L R 3 10,U R 5 8" (movement direction, facing direction, distance in tiles, walking speed) lets you chain movement actions each with their own velocity and orientation. Even if npc_look and npc_move are separate, those other advantages still seem considerable.

**Comment by xirsoi** [comment]
I don't think the having npcs do complex movements over very large maps is something we need to be concerned about. Even if a map is huge (1000x1000 tiles, or something), the viewport is relatively small.

**Comment by Qiangong2** [comment]
What would we use for the speed? We shouldn't need complex speeds. Something like this, maybe?:
1=walk
2=run

**Comment by MirceaKitsune** [comment]
@Qiangong2 Normally I'd advocate for a bigger selection of speeds, like say 1 - 16 to go with a classic range. However if we only had two speeds, we could use capital letters to specify running in a simple letter list! So "RRRrrrUUd" would mean "run 3 tiles to the right, then walk 3 tiles to the right, then run 2 tiles up, then walk 1 tile down".

**Comment by Qiangong2** [comment]
@MirceaKitsune That seems like an easier method. What do you think @bitcraft？

**Comment by ShadowApex** [comment]
@MirceaKitsune @bitcraft While I like the use of capitalization for running vs walking, I think we should also try to keep actions as simple and intuitive as possible. Preferably, it would be nice for people to look at existing map actions and get an idea about what they do, without having to refer too much to the event action reference page. 

I would even say it might even be easier for map creators to see `npc_move up,up,down,left,right` than `npc_move UUDLR`, simply because it's more clear to a new map creator what that action is doing.

That's my thoughts on this feature, but I'd really love to hear more from @Sanglorian and @Qiangong2 about this kind of feature, since they've been contributing most of the maps lately. Ultimately, we should cater these features to our map creator's preferences.

**Comment by Qiangong2** [comment]
@ShadowApex It seems to me, that even though `npc_move up,up,down,left,right` may look easier, if you have a lot of movements (say, more than 5)， it would be a lot more complicated.

Maybe something like `npc_move up,3,right,1R` would be a good compromise. It would have to look for up, down, left or right vs a number and the R would mean run. Whereas it would default to walking.

**Comment by MirceaKitsune** [comment]
@ShadowApex That shouldn't be a problem. Especially since multiple strings could be supported so people can use what they wish, for instance "up" "U" and "N" (for North) or "1" (1st integer in clockwise direction) can all mean up.

Other than that though, especially if you support an intuitive definition over a simple one, I'm kinda sticking with my idea of having a comma separated list of parameters each in the form "direction_walk direction_face number_of_tiles walking_speed". I think something like `npc_move up up 5 10,left down 3 8` offers most flexibility, and it shouldn't be too complex either especially if later parameters are optional. Was curious what you think about that approach as well.

**Comment by bitcraft** [comment]
In general, I'm not a huge fan of overloading.  Commands that support too many optional parameters are difficult to manage and use, IMO.  I think it would be better served by breaking it down into multiple commands.

To support strafing, or movement with changing face:
```
# will always change facing
npc_move 1 up, 3 left

# will never change facing
npc_slide 1 up, 3 left
```
I'm not happy with the word "slide" to move without changing face, but I also don't like the word strafe.  Any ideas?

Another sample, note the one optional parameter for moving, the number; if left out, it will be implied to be one.
```
npc_speed 5
npc_look left
npc_move 1 up, 2 left, 3 right, 10 down
wait 10
npc_speed 10

# demo optional tile number
npc_move left, up, 3 right, down
```

Finally, with this simple syntax, it would be possible to drop the comma between movements:
```
# below are the same, and can be easily adapted in code (no special processing)
npc_move 1 up, 1 up, 1 up, down, 3 left
npc_move up up up down 3 left
```

Opinions?

**Comment by MirceaKitsune** [comment]
`npc_speed 5
npc_look left
npc_move 1 up, 2 left, 3 right, 10 down
wait 1
npc_speed 10
npc_slide 30 right  # GTFO`

I like this format actually! Definitely no objections from me there. It keeps the tile number customizable as I believe it should be, while keeping things simple and not crammed into one function like you said.

**Comment by bitcraft** [comment]
Also, undiscussed is the "move to", and "move by" differences.  Currently "npc_move" is all relative movements.  

I can see value in a "move to" command.  For example, using relative movements requires you to adjust them every time the npc position changes.  The pathfind command can be used, but the path isn't always going to be the same.
```
npc_speed maple, 10
pathfind maple, 10, 12  # run away!
```

To support refined movement to exact tile positions, you need to break the commands up along each axis, since NPCs cannot move diagonally.  Maybe something like this works?
```
npc_speed maple, 10
npc_move_to maple, x 10, y 12
```
The above command will first move along the x axis to tile column 10, then along the y axis to row 12.  The result is the same as pathfinding, but you have more control over the path the npc takes.  The syntax is an axis (x or y), followed by the absolute value on that axis.  Multiple movements can optionally be separated by commas.
```
# same
npc_move_to x 10, y 12
npc_move_to x 10 y 12
```

**Comment by Qiangong2** [comment]
You could always use
`npc_sidle up`
-__-

Personally, I think it would be better if we included speed on the same line as the movement, like when you create an npc, you don't have a different command for wander/stand.

**Comment by Sanglorian** [comment]
Thanks for the summons, @ShadowApex. It's been interesting to follow this discussion.

Thinking through what I would script, I think my needs are limited to:

* Two speeds (walking, running)
* Possibly strafing, but with the default being to change facing to match the direction moved
* Relative movement only (I don't envisage a circumstance where an NPC's position is unknown at the time I need them to move somewhere)
* Fairly simple scripts

Given this, it's probably easiest for me if the syntax is simple and assumes walking unless otherwise specified. During a scripted scene, I imagine moving would often be interspersed with dialogue, and would not be very complicated. 

For example, here's how I imagine a scripted scene working in pseudocode:

```
freeze Protagonist
create Male Enforcer at 0,0 (safely outside of viewport)
Male Enforcer walks right 5, up 2, right 2
Male Enforcer says: "XXX"
Male Enforcer walks left 2, down 2, left 5
destroy Male Enforcer
unfreeze Protagonist
```

And for an ordinary NPC:

`Cat Girl walks left 3, pauses 1, right 5, down 2, pauses 2, up 3, left 2, pauses 1, down 1, repeat
`
Given that, pretty much any of the formats described suit me, but I'd prefer to not have overloading since I'd rarely if ever use anything other than npc_move, npc_pause and npc_face

**Comment by bitcraft** [comment]
@Sanglorian I like the free/unfreeze commands.  We should definitely have them at some point.

**Comment by bitcraft** [comment]
here's the final draft for the commands:

```
npc_face left
npc_move 1 up, 2 left, 3 right 10, 10 down
wait 1
npc_slide 30 right 10
```

* there is already a npc_face command (i was using the word look, my mistake)
* movement speed is the only optional parameter for movement
* speed will be parsed, but won't affect the speed until we figure that out (another issue)
* there isn't much interest in absolute movement ("move_to") so i will shelve that for now

Final detail: should the quantifier come before or after the tile direction; ie which do you prefer?
* ```npc_move 10 up```
* ```npc_move up 10```

**Comment by MirceaKitsune** [comment]
@bitcraft `npc_move up 10` feels cleaner and more logical to me, as you're basically saying "move up by 10". Otherwise I'm not sure if having the speed as an optional parameter makes sense at this point, over having a separate `npc_speed 10` command setting it instead.

**Comment by Qiangong2** [comment]
I feel like `npc_move 10 up` would be better as it fits with other commands. for instance in create_npc it has: 
`create_npc npc_maple,32,15,maple,stand` 
not 
`create_npc npc_maple,stand,maple,32,15`

**Comment by bitcraft** [comment]
If speed is left out of the move command, then the direction and quantity could be in arbitrary order.  In any case, I would say that after we get all the basic commands implemented, then we could do an audit and determine a consistent structure for commands.  That being finialized, somebody (me?) could write a sed/awk script to rewrite the map commands to the proper format (i have done this a few times for the json).

I have these changes implemented right now, but i will be testing them over the next week or so before making a PR.  Thanks for the input everyone.

**Comment by Qiangong2** [comment]
@bitcraft Is there a reason your PR was not commited?

**Comment by bitcraft** [comment]
It was opened by accident.  I need to clean it up before opening a PR.  For example, spelling errors, old comments, etc.  I also tend to make many 100 commits so I will squash them into a since commit for the PR, instead of adding a bunch of noise to the commit log.

Most of my testing is done.  Thursday or friday I will open the PR again.  Its a bit more than just a couple event actions, as you will see.
