### ISSUE TITLE
instructions to install and play on Mac no loner valid

### ISSUE THREAD

**Issue by AllanOcelot** [Tuxemon/Tuxemon#322]
Trying to install and play on Mac ( El Captain ) no longer work.

Following all steps as instructed, I get this error whilst trying to run Tuxemon:
`Allans-MacBook-Pro:tuxemon allan$ ulimit -n 10000; python tuxemon.py
-bash: ulimit: open files: cannot modify limit: Operation not permitted
Traceback (most recent call last):
  File "tuxemon.py", line 59, in <module>
    from core.main import main
  File "/Users/allan/Documents/tuxemon/core/main.py", line 33, in <module>
    from . import prepare
  File "/Users/allan/Documents/tuxemon/core/prepare.py", line 38, in <module>
    import pygame as pg
ImportError: No module named pygame
Allans-MacBook-Pro:tuxemon allan$ `

**Comment by bitcraft** [comment]
Looks like pygame is not found.  Did you get any errors install pygame?

**Comment by bitcraft** [comment]
Also, please make sure you are using the development branch.  We have made a lot of changes, just haven't merged to master yet.  Basically, "master" is stable, but is often several months out of date, since moving all the development changes and squashing bugs is slow.

https://github.com/Tuxemon/Tuxemon/blob/development/README.md
