### ISSUE TITLE
Grass doesn't draw correctly

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#356]
Grass tiles are not sorted correctly before drawing, so grass tiles will cover the top of tall sprites, like the player.

**Comment by MirceaKitsune** [comment]
Grass does seem to draw properly for me; The lower half of the tile covers the player, whereas the upper half is drawn behind the player sprite as it should.

The only issue I'm seeing is with this order looking wrong when the player is walking through grass vertically rather than horizontally; It will appear as if the lower half of the grass is cutting through the player, due to the direction of the movement.

![screenshot_20171026_203900](https://user-images.githubusercontent.com/825418/32068568-5459f092-ba8f-11e7-9eb1-5e1c66c91f07.png)

**Comment by bitcraft** [comment]
partially fixed with latest pyscroll (2.17)  some more tile sorting is needed to get more correct rendering of the top sprite of the grass.

**Comment by bitcraft** [comment]
Fixed with latest pyscroll and tall sprites support.
