### ISSUE TITLE
Save game while poisoned

### ISSUE THREAD

**Issue by andrew-lei** [Tuxemon/Tuxemon#411]
Game will not save when poisoned. This is because tuxemon.core.components.technique.Technique is not JSON serialisable and tuxemon.core.components.save.save's json_data["monsters"][index]["status"] is a list of Techniques.

This seems to be fixed if save_monster and load_monster have checks for key == "status" and repeating the code for "moves", or instead of

(in save_monster)
```python
if key == "moves":
    save_data["moves"] = [i.slug for i in mon.moves]
```

```python
if key in ("moves", "status"):
    save_data[key] = [i.slug for i in getattr(mon,key)]
```

and

(in load_monster)
```python
if key == "moves":
    mon.moves = [Technique(i) for i in value]
```

```python
if key in ("moves", "status"):
    setattr(mon, key, [Technique(i) for i in value])
```

**Comment by bitcraft** [comment]
Yeah it’s a known issue.  What needs to happen is a overhaul of the save system, which is why it’s been put off.  Basically, all objects which can be saved need to implement a method which returns their internal state as a python object.  Once that is done, saving and loading will be much less problematic.

**Comment by bitcraft** [comment]
Related #265

**Comment by kerizane** [comment]
https://github.com/Tuxemon/Tuxemon/pull/417
