### ISSUE TITLE
You are not obliged to have a Tuxemon from professor

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#475]
I don't think it is intended by coders also because in the dialogues it is obvious that NPCs take for guaranteed that you have at least a Tuxemon. So:

* you can go in the Tuxcenter and the woman will restore your inexistent Tuxemons
* knight says that you already have one (what if I already catched some other Tuxemon?)
* Misa says that you have an illegal Tuxemon

**Comment by Qiangong2** [comment]
Honestly, we should dig more into this. It seems more like a story-related problem. The discord or forum would be better for that. However, there is no way (without "cheating") to obtain a Tuxemon before meeting the professor since the only other way to receive Tuxemon at the moment is if you can catch one. Which you cannot do without already having a Tuxemon.

**Comment by bitcraft** [comment]
The berry guy cant fight you until we implement trainer battles.

**Comment by airon90** [comment]
> The berry guy cant fight you until we implement trainer battles.

Not true. If you have a Tuxemon a battle against a wild Tuxemon starts

**Comment by Qiangong2** [comment]
A simple fix for it would be to have a "construction worker" block the road out until you have a Tuxemon. I don't know if there is a condition that checks for Tuxemon, but I think there is.

Also, @airon90 you CAN battle without tuxemon, but only if you give yourself one through the debug controls. Not through the main game.

**Comment by xirsoi** [comment]
@Qiangong2 or @Sanglorian , can you confirm whether this is still an issue with the story?

**Comment by Qiangong2** [comment]
Just tested and yes it is @xirsoi

**Comment by bitcraft** [comment]
There is a param on the python side that allows players to close choice dialogs by hitting cancel/escape.  Would it be safe to assume that all dialogs from the game scripts should require a choice?  I'm leaning toward yes here, since it is less ambiguous for players to choose something, even if there is a "no" option.  If yes, then the solution is simple; edit the dialog choice action and set "escape_closes_menu" to False (going by memory here, the option may be slightly different).

**Comment by xirsoi** [comment]
I don't believe this is an issue any longer. The ChoiceMenu defaults to escape_key_exists = false and nothing that makes one sets that to anything else.

The campaigns have also changed a lot in the last year and I don't think you can proceed without a Tuxemon anymore.
