### ISSUE TITLE
A new idea

### ISSUE THREAD

**Issue by toxub23** [Tuxemon/Tuxemon#476]
If you would like to develop Tuxemon even more, I would suggest to move it to C # and use the Godot Engine. This combination would give a lot of possibilities. C # can use languages like Python, Ruby, R or others so it's really amazing and helpfull. For this Godot has a cooperation with Enjin so you can easily enter eg trade items in the game using cryptocurrency. If you wanted it, I could help you with rewriting to C # language and using Godot Engine. I like Python myself and I use Python 3.7, but C # and Godot are simply better for computer games and PyGame will not do it so good.

**Comment by bitcraft** [comment]
Thank you for your opinion!  Tuxemon will likely stay a python project for the foreseeable future.

**Comment by AndyMender** [comment]
@toxub23 I think it would be even simpler to use GDScript, instead of having to rewrite the code base in C# to interact with the Godot Engine. [Tanks of Freedom](https://github.com/w84death/Tanks-of-Freedom) does exactly that, leveraging the power of the Godot Engine fully.

The clear advantage here is that GDScript is similar to Python so the transition is less dramatic.
