### ISSUE TITLE
Translations need to be fixed

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#490]
Some translations need to be fixed. It causes problems (e.g. it blocks #477)

* [ ] @Clonewayx  @chylex for cz
* [ ] @tamashihoshi @HugopGhost @tobim91 for de
* [ ] @IBPX for es_MX
* [ ] @marius851000 @druz320 for fr
* [ ] @frecor94 for no_NO
* [ ] @HugopGhost for pt_PT and pt_BR
* [ ] @nikitakurylev @chiefexb @stas730 for ru_RU

**Comment by kerizane** [comment]
What exactly needs fixing?

**Comment by bitcraft** [comment]
Thanks for the list @airon90.  Just a note, sometime in the future, all translations will be broken as the locale system is updated.  For now, I'd like to pause on locale fixes until the big PR is merged, as it might create more work for @AndyMender (doing the locale system fixes).

When its merged, we can come back and find missing/broken translations.

**Comment by tamashihoshi** [comment]
@bitcraft @airon90 Then, I shouldn't do translations for now I suppose..? Or should I translate the current state nevertheless?

**Comment by hugonun** [comment]
Hello, I am the former pt/de translator. It has been a while since I checked this project.

Regarding pt_BR and pt_PT, while both are the same language, it is used in different ways. It is hard to explain, but a pt_BR user notices when something is translated to pt_PT or pt_BR, and not having it in their favorite PT language can make the user switch into another language (English f.ex).

This can be the same scenario on es_MX and es_ES. As for pt_BR, I made it hoping that a fluent pt_BR speaker would take care of the translation, since I don't really know it. That was 2years ago, pt_BR can be removed. For es_MX and es_ES, imo the best thing to do is to leave the es_MX translated parts, and replace the English parts with es_ES.

**Comment by bitcraft** [comment]
@vnmabus thats very possible!  before merging the translations, I will run the diff through google translate to spot check it, but beyond that, i can't make any promises that the translation is good....just that it works.  I think that in the future, if translations become really active, we will have a vote on PR from native speakers before they are merged.  Until then, its just faster/easier to accept whatever is given to us.

I'll ping you in this thread when we can start translation work again.

**Comment by IBPX** [comment]
@airon90
> * [ ]  @IBPX for es_MX

I didn't do this translation, I just renamed it from sp_US to es_MX.
