### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#57]
Just wondering, is supporting python 3 on the roadmap?

**Comment by ShadowApex** [comment]
Being Python 3 compatible would definitely be a plus, especially since Ubuntu [plans on removing Python 2.x from the default installation in 16.04](https://wiki.ubuntu.com/Python/FoundationsXPythonVersions) (Debian also plans to do this in their future releases). I noticed that PyTMX uses the sixes library for Python 2/3 compatibility. I think it would be worth doing something similar for Tuxemon.

**Comment by ShadowApex** [comment]
Implemented in merge request  #74

**Comment by benneti** [comment]
I think this issue should be reopened, because the current version does not work with python 3. I will try to fix this in a few weeks myself when i have some more spare time.

**Comment by kerizane** [comment]
Why don't we move completely to py3.7?

**Comment by bitcraft** [comment]
I believe that android only supports python2.  If our builds on android will support 3, then i don't see any reason to continue to support py2.

**Comment by kerizane** [comment]
I noticed that, worth looking into.
