### ISSUE TITLE
Battle check needs to be added

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#574]
Right now, you can battle Leila continuously in cotton town because it never checks if you battled or not

**Comment by Russell-Tran** [comment]
Hi! I've been working on this, but have been struggling with the implementation a bit. My solution involves editing `npc.py` and `start_battle.py`, and I've gotten it to work within a given (session, map.tmx) of the game, but I can't get it to persist in the save files, nor persist if I leave the `mapA.tmx` for `mapB.tmx` and then come back to `mapA.tmx`.

I think this might be because the states of actually-non-playable NPCs are not actually being kept track of anywhere, but it could be because I'm not familiar with the codebase. It seems that saving and loading the game only triggers the functions `NPC.get_state()` and `NPC.set_state()` on behalf of the playable protagonist (where the player's protagonist is called an "npc" because it's an instance of the NPC class).  @bitcraft  thoughts?

**Comment by bitcraft** [comment]
> perhaps it might also be a good idea to separate the protagonist from the NPC class.

I don't think its a good idea to make the player any different from other NPCs.  There is a huge benefit of treating players and other NPCs the same, since any game actions can apply to both without changing the code.  Could you elaborate?

> but I can't get it to persist in the save files

this is what "game variables" are for.  ill admit i don't work in the game script much, but i would think that what should happen is after the battle, check the game variable `battle_last_result` and set a game variable such as `hasBattledLeila=True`.  @Qiangong2 is there an issue with this approach?  Of course the scripts don't work exactly like that.  You would need a 2nd event to watch the `battle_last_result` value on that map and then set `hasBattledLeila=True` if the battle was won.

**Comment by Qiangong2** [comment]
That's exactly what I was hoping it would be. There would also need to be a check if you lost that would send you directly to the last Tuxemon Center you visited. That way, your Tuxemon can heal

**Comment by Russell-Tran** [comment]
> perhaps it might also be a good idea to separate the protagonist from the NPC class.
>> I don't think its a good idea to make the player any different from other NPCs. There is a huge benefit of treating players and other NPCs the same, since any game actions can apply to both without changing the code. Could you elaborate?
Definitely agree. I think I was more caught up on the naming convention because it seemed silly to have a "player" be a "nonplayable character", and that a player class might need to keep track of more information than an NPC class would. But I actually just discovered that there's a `Player` class which extends `NPC` (in `player.py`), so actually we're all good.
