### ISSUE TITLE
Should level up multiple times if there's enough exp

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#579]
If you have enough exp then you should gain multiple levels, not just one.
This could happen if a low-level tmon helps defeat a high-level one.

**Comment by MirceaKitsune** [comment]
I can see where the problem is but need to think of the math to solve it: The level_up function in [monster.py](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/monster.py) does `self.level += 1`. Easiest solution seems like checking how many levels the new exp can get you and adding that amount instead.

**Comment by MirceaKitsune** [comment]
#587 should fix this. Please test it to be sure: I don't currently have a setup that will give my tuxemon enough exp to gain over 1 level at once.
