### ISSUE TITLE
Movement not cancelled by dialog

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#584]
If you're walking and dialog is triggered the player will keep walking in that direction.
```
 <object id="134" name="example" type="event" x="48" y="48" width="16" height="16">
   <properties>
    <property name="act1" value="wait 3"/>
    <property name="act2" value="translated_dialog column1"/>
   </properties>
  </object>
```
We should either stop the movement or allow control of the movement during dialog.
Allowing movement seems a bit weird, so I think we should stop the movement.

**Comment by bitcraft** [comment]
Yes movement should be stopped.  This regression comes because in the past, the state manager would reset the controls for each state change.  With the input refactor, I thought that we should manually trigger the input reset because we may have states that would want to keep the inputs from the previous one.  I may be wrong here though.  The solution is to clear the inputs before the state changes.  Alternatively, we could just go back to the old behavior of resetting the controls between states.  Im not really sure. 

```
# call to send virtual "key up" events before changing states.
self.game.release_controls()
self.game.push_state(...)
```

**Comment by xirsoi** [comment]
I think it might be best to clear the controls between states. It would be unpleasant to accidentally select an option in a menu or dialogue because i happened to be pressing the right button immediately before that thing popped up.

**Comment by bitcraft** [comment]
ok.  i guess let me ask this for sanity: @kerizane @xirsoi @Qiangong2 @MirceaKitsune do you think there will ever be a situation where the game state changes (dialog, menu, map view, etc) AND you wouldn't want to clear the player controls?  if the answer is "no", then ill go back to the behavior of "clear inputs between state transitions"

**Comment by Qiangong2** [comment]
The only instance I can see is if you are being "guided" through an area by an npc and instructions show up as you move.

**Comment by kerizane** [comment]
Can't think of anything

**Comment by MirceaKitsune** [comment]
I don't see why that would be a problem either, so no. It's actually an annoyance in many applications of various types: Having something pop up then process a key you were already holding down.

**Comment by bitcraft** [comment]
Ok, i think the consensus is to revert it

**Comment by bitcraft** [comment]
fixed 3acf21216fbcaa7a2023a69fc7ec50a724d93d07 3d6841147fc9d2ecf2bc1f423a2ee3b1dfe1e1b2
I've reverted back to the previous behavior of releasing/resetting controls when the state changes.  i've also added explicit locking and unlocking of the player controls when the state changes, as well as stopping the player.  ive tested this and so far have found it to work great.  im still not happy with resetting controls between state changes because it seems like a hack, but ill try to fix that later.  @kerizane do you mind testing this again?

**Comment by kerizane** [comment]
Fixed

**Comment by bitcraft** [comment]
Thank you!
