### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#59]
How is Tuxemon tested?  Are there unit tests, or some sort of integration test suite?

**Comment by ShadowApex** [comment]
Right now Tuxemon is only tested manually for the most part. I did set up some very basic Travis CI jobs but, for the most part, it doesn't really run any tests. In the future it would be very nice to have automated tests through Jenkins/Travis. 

One potential issue is that some components may need a Pygame window initialized in order to run. Early on in the game's development I didn't do a very good job at separating the game's business logic from the presentation layer, which has carried over from those early days. Refactoring those parts has been an ongoing effort (e.g. the `world_state_refactor` branch).

**Comment by bitcraft** [comment]
Travis cannot use pygame (I've tried), except if you can maybe execute everything in a framebuffer, and set the right SDL environment flags.  Personally, I don't see a great benefit to testing in a framebuffer compared to the effort involved in setting that up.  IMO, the most gains will come from testing parts of the API using unit tests.  Skip implementing the entire game and focus on parts that you know will get messed up often as the are implemented.

...of course this means you need to design before you code,  TDD is really useful.  If anyone doesn't know python unittesting, I will be implementing tests for the state system as I develop/design it for tuxemon.  Then travis can execute and verify them.

I've looked over the action plugins and I think they would be a good target for testing.  Design the test case first, then the code.  The code seems to be stateless, and could be trivial to test.

Anyway, this is just my opinion.  Hope it inspires people.  ^_^

**Comment by ShadowApex** [comment]
This sounds good. :+1:
