### ISSUE TITLE
Screenshot stored in text-only save file

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#599]
There appears to be an issue with generating save files: Although the slot#.sav file is supposed to be text only and contain just game properties, it includes a gigantic field which seemingly stores the screenshot, composed of constantly repeating groups of letters. This not only makes the file 3.5 MB in size, but certain text editors lag or have issues opening it. I also don't see why a screenshot must be stored in the save file, there's already a corresponding slot#.png file for every save slot.

![save](https://user-images.githubusercontent.com/825418/72011218-0af16f00-3262-11ea-8cee-ac1e9ae77f5e.png)

**Comment by bitcraft** [comment]
3.5mb is not a huge?  i agree it could be smaller, but i don't really see a problem here.  this was implemented because the screenshot files outside of the same file caused a ton of problems if they were missing or modified.  embedding them in the save file solved a few really annoying issues.

**Comment by MirceaKitsune** [comment]
The size isn't that big of an issue in and of itself. The main problem is opening the save file in a text editor, in case you need to modify variables to do testing for instance. KWrite opens it as read-only by default due to breaching the size limit... Geany (which I use for development) can edit it, but it lags and takes a second for any command to update while it's open.

Perhaps we could do what the monster system does: If an image is missing, use the placeholder question mark to make that obvious without causing a crash.

**Comment by kerizane** [comment]
Yeah, not a fan of storing it as a string.

We already have fallback, if you delete the key/value pair then we just show a black box.

**Comment by bitcraft** [comment]
using a json editor will reduce this problem somewhat because you can collapse the objects.  i suggest you try that instead of notepad or whatever.

have you tried editing saves in other games?  stardew valley's save files are also very large and contain tons of data.  and yet, there is a huge community of people who mod the save files despite the problems with it.  the tuxemon saves are only likely to get larger as we add more variables and features.  editing them will always be problematic because they are json.  embedding the image was a feature we agreed on and im not really willing to go back on it because this is much better overall.

we could investigate storing the screenshot data as a smaller size and compressed with jpg to reduce the file size, but honestly this is a non-issue to me.

**Comment by bitcraft** [comment]
another suggestion: turn off line wrapping

**Comment by MirceaKitsune** [comment]
I don't have a json editor though I should get one as it would help with a lot of things. When it comes to settings files I typically open them in a normal text editor.

Overall it's a little weird to open a file text that should only have a few clean settings, but there's just this one field that completely bombs it with something huge.

In the meantime I fully agree with at least disabling line wrapping, so at least it doesn't look so messy.

**Comment by bitcraft** [comment]
ok.  im going to close this issue then unless there are any other objections.  feel free to open another pr which reduces the text blob size, or moves the screenshot to the end of the file, etc.

save files are not really meant to be "text" files.  they contain save data.  being human editable is only a side-effect and a deliberate one.  we could choose any number of other formats which are completely non human readable if you would prefer.
