### ISSUE TITLE
Use default (64px) sprites for trainer battles

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#604]
In older pokemon games, the way trainer battles were done is by first showing the trainer sprite in the battle, and then fading out when the Pokemon is thrown into battle. I think something similar should be implemented here since we already have the 64px sprites

**Comment by bitcraft** [comment]
For people not familiar with the older games, do you have a link to a video (with timestamp?) which shows what it should look like?

**Comment by Sanglorian** [comment]
Sure thing - https://youtu.be/gYwo0aVwSc4?t=42

Essentially:

1. Show exclamation mark over overland sprite.
2. Display trainer's opening dialogue. When player presses RETURN,
3. Transition to black. Start playing trainer score instead of map score.
4. Transition from black. 
5. Trainer sprite "slides" in from left hand side.
6. Dialogue: "[CLASS] [NAME] challenges you to a battle."
7. Trainer sprite slides out from right hand side. 
8. Monster appears.
[Battle]
1. "[PLAYER NAME] defeated [CLASS] [NAME].
2. Display trainer's closing dialogue. 
3. "[PLAYER NAME] wins $#.

**Comment by Qiangong2** [comment]
We don't necessarily have to do the sliding out in battle. I believe that it would work if we just have the 64px trainer sprite show up when the battle starts, it will say [trainer] challenged you, and then the sprite would fade out when the Tuxemon appears

**Comment by bitcraft** [comment]
@Sanglorian nice work detailing the steps to make it happen, thats super helpful!  thank you!

**Comment by xirsoi** [comment]
I'll get this added in.

**Comment by xirsoi** [comment]
Done.

**Comment by Qiangong2** [comment]
Just to clarify, in battles, the npcs slide in from the side now in trainee battles?

**Comment by xirsoi** [comment]
Indeed they do.
