### ISSUE TITLE
npc_freq request

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#651]
As funny as it is to have an npc move at 0.2 speed, We should really have a movement frequency action to work with npc_speed and wander

It's nearly impossible to talk to the professor's wife

**Comment by MirceaKitsune** [comment]
Have you tried setting npc_speed to a lower value, as well as the npc_wander frequency? I'd rather not change the core functionality personally, but see sense in the defaults being tweaked. If that would be better, the default wander speed could be set to 0.5 instead, by editing this line:

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/event/actions/npc_wander.py#L74

**Comment by Qiangong2** [comment]
Honestly, I was thinking it would be better as an optional argument for npc_speed

**Comment by MirceaKitsune** [comment]
It could be done that way too? Not sure if a good idea still: NPC speed is different from telling the NPC to wander around.

**Comment by Qiangong2** [comment]
One reason I'd want to set it separately is because at some point we may want a Tuxemon chasing its owner, or vice-versa

**Comment by bitcraft** [comment]
ill weigh in on this one, i don't like overloading actions with lots of arguments, and in this case i prefer setting the wander frequency in an more related action  (`npc_wander`).

it is also a bit more logical to set with `npc_wander` since setting it with npc_speed does nothing until you actually start the wandering action.  Im all for more sensible defaults though, and also changing the speed of the wife so we don't have to "trap her in a corner and smash the enter key rapidly to open a dialog"  :smile:

**Comment by MirceaKitsune** [comment]
I too noticed that catching her to trigger the dialogue is a bit difficult, though for some reason I thought it's just me having bad luck. I agree this can get a little bit annoying with NPC's that have dialogue.

I didn't really think about this when I did the wandering code: The limits and defaults were based on what made most sense to see. At 0.5 (minimum) the NPC walks all over the place as if in a panic, while at 5 (maximum) they only walk occasionally. I defaulted to 1 as it resulted in the most logical looking movement patterns. I'm wondering if it might solve this to use 2 or 3 as the default instead.

There could be another solution too: Allow talking to an NPC while it's moving between tiles, if you're looking and pressing ENTER toward both the old and new position. So if you catch an NPC in-between tiles, interacting with either of the two positions would allow the trigger to fire.

**Comment by bitcraft** [comment]
let me just put this out there..... the wife is an important npc do we really need her to be wandering?  why not turn it off for her since its annoying to test the game while chasing her?  we can enable it for some other non-essential npc (and set the default to something lower).  imo, most games dont have wandering npcs so i'm really sure we absolutely need it here.

**Comment by MirceaKitsune** [comment]
That would be fine too, she doesn't need to wander. I added wandering to her as a way of showcasing the feature and having a test case handy. Plus she just sits there in the middle of the room which isn't very logical, so it further felt like this made sense at the time.

I would like to have at least one other NPC wandering however. I often find that when a feature doesn't have a test case handy for people to see, it can break without anyone noticing. This happened for attack statuses (eg: poison) which got removed from the default techniques... when I added them to my game I ran into two crashes that were since patched. So it might be a good practice to have a use case of everything in the default game especially around the first levels.

**Comment by bitcraft** [comment]
Ok cool.  Sounds like we are agreeing to disable wandering for the wife and adding a new nonessential npc that wanders.

**Comment by MirceaKitsune** [comment]
Sure. We could add a new NPC outside... around the Tuxemart / Healing Centre perhaps, to also liven up the place. They can have a short and simple dialogue so moving interactions can also be tested.

Also I'd move the professor's wife to the couch: I think it makes a little more sense than her standing in the middle of the room constantly looking down for no reason.

**Comment by bitcraft** [comment]
tbh, id rather not move the wife right now,  its part of my standard testing run.  with so much to do on the game overall moving around npcs doesn't seem like a huge priority.

**Comment by bitcraft** [comment]
Changed the mom's wander freq to 3.  Still need to stop the wife from wandering to close this issue.

**Comment by bitcraft** [comment]
I'm going to close this since wandering wife is only a problem when debugging.  When debug maps are created, it won't be an issue.
