### ISSUE TITLE
Record number of steps taken by the player

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#710]
for #700, there should be a game variable that
* is incremented each time the player moves one tile
* is not incremented when pushing a wall
* is not incremented when the player is pushed or moved by another object, npc, or action
* must be tried with the controls; ie the player intended to move the npc, and the npc moved, so gain one step

**Comment by vch9** [comment]
Hello, I'd like to help you on that one, where would you store the game variable ?

**Comment by bitcraft** [comment]
@vch9 awesome!  welcome to the team.  "game variables" refers to a dictionary on the player class.  this dictionary represents the game state and can be modified anywhere there is a player object.

**Comment by vch9** [comment]
@bitcraft The game is fun, i'll try to help a bit!  
I only have one issue with this step counter,  I don't understand where do you  
setup game variables dictionary for the player.   
Since i want to increment the number of steps, I would like to initialize it to 0.  

The key for my dictionary could be added the first time the player moves,  
but the test whether the key is in the game_variables will be done every time there  
is a movement?

**Comment by bitcraft** [comment]
If i were doing it, i would set the steps game variable to 0 inside `Player.__init__`.  You should not be checking if it exists each time.  This is considered a core feature and its not needed to check.  Existing save games will be impacted though, so look at `save_upgrader.py` to add a migration step (just add the variable to the save).

**Comment by vch9** [comment]
@bitcraft Thank you for the help :)! The PR is ready.
