### ISSUE TITLE
Errors in po file?

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#761]
I am checking en.po file and I have some questions, which may be errors:

1. Is it correct that key names have "\n" at the end? ([example](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L1515))
2. [xerogrunt2](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L1268) and [xerogrund2](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L1265) exist. Before deleting the second one (and changing also [xerogrund1](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L1262) to xerogrunt1) check that no "xerogrund1" and "xerogrund2" are called by the game
3. Some keys ([example](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L130), old keys) have ```{keyname}``` and some ([example](https://github.com/Tuxemon/Tuxemon/blob/997a3a87ed18e210e2e9869a422272372cc841fa/mods/tuxemon/l18n/en_US/LC_MESSAGES/base.po#L1942), new keys) have ```${{keyname}}```. If it is an error, please fix it to the correct one. If both are correct, I suggest uniforming the system

**Comment by kerizane** [comment]
1.

If a key ends with \n then this tells the game to treat the message as a multi-box message.
A new box will be created for each \n. 
So instead of msg1, msg2, msg3 you have msg\n

If you don't have the "\n" in the key then the \n is treated a normal newline character.

**Comment by kerizane** [comment]
2.

xerogrund2 is on route1

**Comment by airon90** [comment]
> If you don't have the "\n" in the key then the \n is treated a normal newline character.

Some keys have "\n" inside the text but don't have it in the key name. Should I add it to every key having "\n"?

**Comment by airon90** [comment]
> xerogrund2 is on route1

So xerogrunD2 and xerogrunT2 are two different people with same name? If so, shouldn't they use the same key anyway?

**Comment by airon90** [comment]
I have some other questions but I will do when I finished translating.

**Comment by kerizane** [comment]
> Some keys have "\n" inside the text but don't have it in the key name. Should I add it to every key having "\n"?

If it looks better that way.

**Comment by Qiangong2** [comment]
Ha! Didn't think anyone looked that close at the maps besides me :D

Yes, xerogrunt and xerogrund are different npcs. That area was designed when we had barely implemented NPCs in the first place. So it was more of an experiment to handle the area and block off a chunk of the map. That's why there are ten in a row. And yes, it looks awkward. It will be reworked.

**Comment by airon90** [comment]
What about point 3?

**Comment by bitcraft** [comment]
I'll have to check that.  I believe that the use of single curly brackets `{foo}` is wrong and we would need to update them.  IMO, fixing template errors not a huge priority right now because there is a plan to move translations to Jinja2 for more features that are not possible right now.  During next dialog change, we can also update the old ones.  I don't think we will need huge changes again after Jinja2 is done.
