### ISSUE TITLE
Changing keys in the config file only adds bindings, doesn't remove default bindings

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#767]
Key bindings found in the config file should override the defaults.  As-is, it just adds bindings to the default.

**Comment by austintian03** [comment]
This issue seems to do with the line `cfg = generate_default_config()` in `config.__init__` before everything else such as parsing and populating the config. 

Since that always calls `get_defaults()` the config is always repopulated with the defaults, which of course re-adds the default bindings to `controls`.

**Comment by austintian03** [comment]
This fixes the issue by making it so that the config is only populated with `get_defaults()` if `config_path` is an actual path in the system. This means I had to `import os.path` in `config.__init__()` which may not be ideal.

Before, `generate_default_config()` always populated the config with `get_defaults()` no matter what, now you can change the config file with impunity (this can create the issue of people messing up the config with erroneous values causing the game to not run, so it assumes people always modify the config with possible values).

**Comment by bitcraft** [comment]
The current way of always populating the defaults each time is a feature so that old configurations are always up to date if an option is added.  In the past, config files would break everytime an option was added or changed and the user was forced to edit it.  It was actually a huge hassle for people and was maybe our #1 asked question for a long time ("so my config is broke, what do i need to do to fix it?)

This change you're proposing seems like it would break that feature, and upgrades to the game would break old config files.  Given that it was a super common problem before, I'm not comfortable with allowing config files to get out of date.

I think we need special case handling for the controls, maybe something like this:
- When searching the config file, look at each value/button/button
- Check if that button/event already exists in the defaults and is mapped
- If existing in the defaults, then delete the existing key from the controls dictionary

Another solution which might make more sense is to reverse the key/values under the controls section (the original way you described it....sorry).  After reversing it, the key would be the internal action (like left, backspace, a, etc), and the value would be a comma separated list of strings.

```
[controls]
up = up, w
down = down, s
left = left, a
right = right, d
a = return
b = lshift, rshift
back = escape
backspace = backspace
```

The benefit here would be that the defaults would be cleanly overridden by the values in the config file because the keys match and it would be less complicated to override....but you would need to parse the strings, and figure out how to map each item in the list.

There may be other solutions, of course, but I don't think I would merge one that allows config files to be broken.  For many people, they don't want to ever edit that file and it can be a hassle to find it because its a hidden file.
