### ISSUE TITLE
Simplification of screen areas

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#85]
I've noticed a trend for code like this:
```python
monster_menu = MonsterMenu(game)
monster_menu.size_x = 200
monster_menu.size_y = 100
monster_menu.pos_x = 500
monster_menu.pos_y = 500
```

This is the exact format for pygame Rects.  I feel that it would greatly simplify defining areas of the screen by using Rects as it is more compact and gives useful functions, like quickly finding the center point, checking overlapping areas, ect.

```python
monster_menu = MonsterMenu(game)
monster_menu.rect = Rect(500, 500, 200, 100)
```

I'd like to convert over this type of code to Rects as I come about it, unless anyone objects.

**Comment by ShadowApex** [comment]
I think this is a great idea. To let you know, I've previously done work on trying to refactor the menu system to make it easier to use in the "menu_refactor" branch. It's been a while since I've worked on it, so merging it to development might be painful, but I'd like to incorporate some of its functionality into the menus.

You can take a look at the refactored menu I've been working on here: https://github.com/Tuxemon/Tuxemon/blob/menu_refactor/tuxemon/core/components/menu/__init__.py#L50

**Comment by bitcraft** [comment]
I can merge that into my branch. Looks like there was a lot of effort put
into it. It would help me if you could make a small list of the overall
changes that need to be migrated. From just a quick look, it seems that the
complicated parts have been broken down functions. Thanks!

**Comment by ShadowApex** [comment]
Yeah, the refactor removed a lot of unnecessary legacy bits and added a lot of helper methods to remove a lot of the code duplication seen throughout the codebase. 

Here's a quick summary of the things I had done:
* Removed unnecessary parameters like `screen`, `resolution`, etc.
* Added init params to construct menus with their size and position upon creation.
* Made the menu inherit from the `UserInterface` class to provide functionality like moving over time and playing background and menu border animations.
* Added `next`, `previous`, and `done` to make menus more state-like. These will probably be deprecated with your changes.
* Broke up some methods into smaller functions for easier reuse and readability.
* Added helper methods like `menu_select_next`, `menu_select_prev`, `set_size`, and `set_position`.
* Made drawing dependent on the `self.visible` property.
* Made input handling dependent on the `self.interactable` property.
* Replaced methods like `draw`, `draw_text`, and `draw_textItem` with a single `draw()` method. 
* Text drawing is done automatically in `draw` after you call `set_text` once instead of needing to pass the text to draw every frame.

**Comment by bitcraft** [comment]
Thanks for the write up.  Details like how text drawing will help make sure there are no regressions.

**Comment by bitcraft** [comment]
I'm going to close this.  My current branch has changes the "pos_x", "size_x", etc variables into pygame Rects.  Updates to the states/menu refactor will be in #72.
